pre-commit:
  jobs:
    - name: lint
      run: bun run lint:fix
      stage_fixed: true

    - name: format
      run: dprint fmt --staged
      stage_fixed: true

    - name: typegen
      run: bun run wrangler types

    - name: typecheck
      run: bun run typecheck

    - name: generate-api
      run: bun run generate:api

pre-push:
  jobs:
    - name: test
      run: bun run test

# Validate commit messages
commit-msg:
  commands:
    "lint commit message":
      run: bunx commitlint --config .commitlint.ts --edit {1}
