pre-commit:
  jobs:
    - name: format
      run: bun run format
      glob: "*.{js,ts,json,md,yml,yaml}"
      stage_fixed: true

    - name: lint
      run: bun run lint:fix
      glob: "*.{js,ts}"
      stage_fixed: true

    - name: typegen
      run: bun run wrangler types
      glob: "*.{ts,toml}"

    - name: typecheck
      run: bun run typecheck
      glob: "*.ts"

pre-push:
  jobs:
    - name: test
      run: bun run test
