#:schema https://mise.jdx.dev/schema/mise.json

[tools]
"cargo:runner-run" = "latest"
biome              = "latest"
cargo-binstall     = "latest"
golangci-lint      = "2.13.2"
lefthook           = "latest"
shellcheck         = "latest"
task               = "latest"
tombi              = "latest"
uv                 = "latest"
wrangler           = "latest"

[settings]
idiomatic_version_file_enable_tools = ["go"]

[settings.cargo]
binstall      = true
binstall_only = true
