#:schema https://mise.jdx.dev/schema/mise.json
#:tombi toml-version = "v1.1.0"

[tools]
actionlint    = "latest"
biome         = "2.5.15"
bun           = "1.4.2"
dprint        = { prerelease = true, version = "latest" }
gitleaks      = "8.24.3"
go            = "latest"
golangci-lint = "2.14.0"
lefthook      = "latest"
runner-run    = "latest"
shellcheck    = "latest"
task          = "latest"
tombi         = "1.7.2"
typescript    = { filter_bins = ["tsc"], version = "latest" }
uv            = "0.12.23"

[tools.wrangler]
version      = "4.147.0"
allow_builds = ["esbuild", "sharp", "workerd"]

[tool_alias]
actionlint = "github:kjanat/actionlint"
dprint     = "github:kjanat/dprint"
runner-run = "github:kjanat/runner"
tombi      = "github:tombi-toml/tombi"
typescript = "github:Microsoft/TypeScript"
shellcheck = "github:koalaman/shellcheck"

[settings]
minimum_release_age_excludes        = [
  "github:kjanat/actionlint",
  "github:kjanat/dprint",
  "github:kjanat/runner",
  "github:Microsoft/TypeScript",
]
idiomatic_version_file_enable_tools = ["go"]
