// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes       bearerAuthContextKey       = "bearerAuth.Scopes"
	OidcAuthScopes         oidcAuthContextKey         = "oidcAuth.Scopes"
	ServiceTokenAuthScopes serviceTokenAuthContextKey = "serviceTokenAuth.Scopes"
)

// Defines values for AuditAction.
const (
	AuditActionKeyRotate   AuditAction = "key_rotate"
	AuditActionKeyUpload   AuditAction = "key_upload"
	AuditActionSign        AuditAction = "sign"
	AuditActionTokenCreate AuditAction = "token_create"
	AuditActionTokenRevoke AuditAction = "token_revoke"
)

// Valid indicates whether the value is a known member of the AuditAction enum.
func (e AuditAction) Valid() bool {
	switch e {
	case AuditActionKeyRotate:
		return true
	case AuditActionKeyUpload:
		return true
	case AuditActionSign:
		return true
	case AuditActionTokenCreate:
		return true
	case AuditActionTokenRevoke:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	AUDITERROR         ErrorCode = "AUDIT_ERROR"
	AUTHINVALID        ErrorCode = "AUTH_INVALID"
	AUTHMISSING        ErrorCode = "AUTH_MISSING"
	INTERNALERROR      ErrorCode = "INTERNAL_ERROR"
	INVALIDREQUEST     ErrorCode = "INVALID_REQUEST"
	KEYDELETEERROR     ErrorCode = "KEY_DELETE_ERROR"
	KEYLISTERROR       ErrorCode = "KEY_LIST_ERROR"
	KEYNOTFOUND        ErrorCode = "KEY_NOT_FOUND"
	KEYPROCESSINGERROR ErrorCode = "KEY_PROCESSING_ERROR"
	KEYUPLOADERROR     ErrorCode = "KEY_UPLOAD_ERROR"
	NOTFOUND           ErrorCode = "NOT_FOUND"
	RATELIMITED        ErrorCode = "RATE_LIMITED"
	RATELIMITERROR     ErrorCode = "RATE_LIMIT_ERROR"
	SIGNERROR          ErrorCode = "SIGN_ERROR"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case AUDITERROR:
		return true
	case AUTHINVALID:
		return true
	case AUTHMISSING:
		return true
	case INTERNALERROR:
		return true
	case INVALIDREQUEST:
		return true
	case KEYDELETEERROR:
		return true
	case KEYLISTERROR:
		return true
	case KEYNOTFOUND:
		return true
	case KEYPROCESSINGERROR:
		return true
	case KEYUPLOADERROR:
		return true
	case NOTFOUND:
		return true
	case RATELIMITED:
		return true
	case RATELIMITERROR:
		return true
	case SIGNERROR:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Healthy  HealthStatus = "healthy"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Healthy:
		return true
	default:
		return false
	}
}

// AuditAction defines model for AuditAction.
type AuditAction string

// AuditLogsResponse defines model for AuditLogsResponse.
type AuditLogsResponse struct {
	Count int `json:"count"`
	Logs  []struct {
		Action    AuditAction        `json:"action"`
		ErrorCode *ErrorCode         `json:"errorCode,omitempty"`
		Id        openapi_types.UUID `json:"id"`
		Issuer    string             `json:"issuer"`
		KeyId     string             `json:"keyId"`
		Metadata  *string            `json:"metadata,omitempty"`
		RequestId openapi_types.UUID `json:"requestId"`
		Subject   string             `json:"subject"`
		Success   bool               `json:"success"`
		Timestamp time.Time          `json:"timestamp"`
	} `json:"logs"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      ErrorCode           `json:"code"`
	Error     string              `json:"error"`
	RequestId *openapi_types.UUID `json:"requestId,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Checks struct {
		Database   bool `json:"database"`
		KeyStorage bool `json:"keyStorage"`
	} `json:"checks"`
	Status    HealthStatus `json:"status"`
	Timestamp time.Time    `json:"timestamp"`
	Version   string       `json:"version"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus string

// KeyDeletionResponse defines model for KeyDeletionResponse.
type KeyDeletionResponse struct {
	Deleted bool `json:"deleted"`
	Success bool `json:"success"`
}

// KeyListItem defines model for KeyListItem.
type KeyListItem struct {
	Algorithm   string `json:"algorithm"`
	CreatedAt   string `json:"createdAt"`
	Fingerprint string `json:"fingerprint"`
	KeyId       string `json:"keyId"`
}

// KeyListResponse defines model for KeyListResponse.
type KeyListResponse struct {
	Keys []KeyListItem `json:"keys"`
}

// KeyResponse defines model for KeyResponse.
type KeyResponse struct {
	Algorithm   string `json:"algorithm"`
	Fingerprint string `json:"fingerprint"`
	KeyId       string `json:"keyId"`
	Success     *bool  `json:"success,omitempty"`
	UserId      string `json:"userId"`
}

// KeyUpload defines model for KeyUpload.
type KeyUpload struct {
	ArmoredPrivateKey string `json:"armoredPrivateKey"`
	KeyId             string `json:"keyId"`
}

// PublicKeyResponse defines model for PublicKeyResponse.
type PublicKeyResponse = string

// RateLimitError defines model for RateLimitError.
type RateLimitError struct {
	Code       ErrorCode `json:"code"`
	Error      string    `json:"error"`
	RetryAfter int       `json:"retryAfter"`
}

// SignRequest defines model for SignRequest.
type SignRequest = string

// SignResponse defines model for SignResponse.
type SignResponse = string

// TokenCreate defines model for TokenCreate.
type TokenCreate struct {
	ExpiresInDays *int      `json:"expiresInDays,omitempty"`
	KeyIds        *[]string `json:"keyIds,omitempty"`
	Name          TokenName `json:"name"`
}

// TokenCreatedResponse defines model for TokenCreatedResponse.
type TokenCreatedResponse struct {
	ExpiresAt *string   `json:"expiresAt"`
	Id        string    `json:"id"`
	KeyIds    *[]string `json:"keyIds"`
	Name      TokenName `json:"name"`

	// Token Plaintext token; shown exactly once
	Token string `json:"token"`
}

// TokenListResponse defines model for TokenListResponse.
type TokenListResponse struct {
	Tokens []TokenSummary `json:"tokens"`
}

// TokenName defines model for TokenName.
type TokenName = string

// TokenRevokeResponse defines model for TokenRevokeResponse.
type TokenRevokeResponse struct {
	Id      string `json:"id"`
	Success bool   `json:"success"`
}

// TokenSummary defines model for TokenSummary.
type TokenSummary struct {
	CreatedAt  string    `json:"createdAt"`
	ExpiresAt  *string   `json:"expiresAt"`
	Id         string    `json:"id"`
	KeyIds     *[]string `json:"keyIds"`
	LastUsedAt *string   `json:"lastUsedAt"`
	Name       TokenName `json:"name"`
	RevokedAt  *string   `json:"revokedAt"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// oidcAuthContextKey is the context key for oidcAuth security scheme
type oidcAuthContextKey string

// serviceTokenAuthContextKey is the context key for serviceTokenAuth security scheme
type serviceTokenAuthContextKey string

// GetAdminAuditParams defines parameters for GetAdminAudit.
type GetAdminAuditParams struct {
	Limit     *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset    *int       `form:"offset,omitempty" json:"offset,omitempty"`
	Action    *string    `form:"action,omitempty" json:"action,omitempty"`
	Subject   *string    `form:"subject,omitempty" json:"subject,omitempty"`
	StartDate *time.Time `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate   *time.Time `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// GetPublicKeyParams defines parameters for GetPublicKey.
type GetPublicKeyParams struct {
	KeyId *string `form:"keyId,omitempty" json:"keyId,omitempty"`
}

// PostSignParams defines parameters for PostSign.
type PostSignParams struct {
	KeyId      *string             `form:"keyId,omitempty" json:"keyId,omitempty"`
	XRequestID *openapi_types.UUID `json:"X-Request-ID,omitempty"`
}

// PostAdminKeysJSONRequestBody defines body for PostAdminKeys for application/json ContentType.
type PostAdminKeysJSONRequestBody = KeyUpload

// PostAdminTokensJSONRequestBody defines body for PostAdminTokens for application/json ContentType.
type PostAdminTokensJSONRequestBody = TokenCreate

// PostSignTextRequestBody defines body for PostSign for text/plain ContentType.
type PostSignTextRequestBody = SignRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAdminAudit request
	GetAdminAudit(ctx context.Context, params *GetAdminAuditParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminKeys request
	GetAdminKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminKeysWithBody request with any body
	PostAdminKeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAdminKeys(ctx context.Context, body PostAdminKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAdminKeysKeyId request
	DeleteAdminKeysKeyId(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminKeysKeyIdPublic request
	GetAdminKeysKeyIdPublic(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminTokens request
	GetAdminTokens(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminTokensWithBody request with any body
	PostAdminTokensWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAdminTokens(ctx context.Context, body PostAdminTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAdminTokensId request
	DeleteAdminTokensId(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPublicKey request
	GetPublicKey(ctx context.Context, params *GetPublicKeyParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSignWithBody request with any body
	PostSignWithBody(ctx context.Context, params *PostSignParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSignWithTextBody(ctx context.Context, params *PostSignParams, body PostSignTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAdminAudit(ctx context.Context, params *GetAdminAuditParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminAuditRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminKeysRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminKeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminKeysRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminKeys(ctx context.Context, body PostAdminKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminKeysRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAdminKeysKeyId(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAdminKeysKeyIdRequest(c.Server, keyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminKeysKeyIdPublic(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminKeysKeyIdPublicRequest(c.Server, keyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminTokens(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminTokensRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminTokensWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminTokensRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminTokens(ctx context.Context, body PostAdminTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminTokensRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAdminTokensId(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAdminTokensIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPublicKey(ctx context.Context, params *GetPublicKeyParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPublicKeyRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSignWithBody(ctx context.Context, params *PostSignParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSignRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSignWithTextBody(ctx context.Context, params *PostSignParams, body PostSignTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSignRequestWithTextBody(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAdminAuditRequest generates requests for GetAdminAudit
func NewGetAdminAuditRequest(server string, params *GetAdminAuditParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/audit")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Action != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "action", *params.Action, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Subject != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "subject", *params.Subject, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.StartDate != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "startDate", *params.StartDate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.EndDate != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "endDate", *params.EndDate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminKeysRequest generates requests for GetAdminKeys
func NewGetAdminKeysRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAdminKeysRequest calls the generic PostAdminKeys builder with application/json body
func NewPostAdminKeysRequest(server string, body PostAdminKeysJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAdminKeysRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAdminKeysRequestWithBody generates requests for PostAdminKeys with any type of body
func NewPostAdminKeysRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAdminKeysKeyIdRequest generates requests for DeleteAdminKeysKeyId
func NewDeleteAdminKeysKeyIdRequest(server string, keyId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "keyId", keyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminKeysKeyIdPublicRequest generates requests for GetAdminKeysKeyIdPublic
func NewGetAdminKeysKeyIdPublicRequest(server string, keyId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "keyId", keyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys/%s/public", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminTokensRequest generates requests for GetAdminTokens
func NewGetAdminTokensRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/tokens")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAdminTokensRequest calls the generic PostAdminTokens builder with application/json body
func NewPostAdminTokensRequest(server string, body PostAdminTokensJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAdminTokensRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAdminTokensRequestWithBody generates requests for PostAdminTokens with any type of body
func NewPostAdminTokensRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/tokens")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAdminTokensIdRequest generates requests for DeleteAdminTokensId
func NewDeleteAdminTokensIdRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/tokens/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPublicKeyRequest generates requests for GetPublicKey
func NewGetPublicKeyRequest(server string, params *GetPublicKeyParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/public-key")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.KeyId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "keyId", *params.KeyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostSignRequestWithTextBody calls the generic PostSign builder with text/plain body
func NewPostSignRequestWithTextBody(server string, params *PostSignParams, body PostSignTextRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	if stringer, ok := interface{}(body).(fmt.Stringer); ok {
		bodyReader = strings.NewReader(stringer.String())
	} else {
		bodyReader = strings.NewReader(fmt.Sprint(body))
	}
	return NewPostSignRequestWithBody(server, params, "text/plain", bodyReader)
}

// NewPostSignRequestWithBody generates requests for PostSign with any type of body
func NewPostSignRequestWithBody(server string, params *PostSignParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sign")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.KeyId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "keyId", *params.KeyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XRequestID != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", *params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Request-ID", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAdminAuditWithResponse request
	GetAdminAuditWithResponse(ctx context.Context, params *GetAdminAuditParams, reqEditors ...RequestEditorFn) (*GetAdminAuditResponse, error)

	// GetAdminKeysWithResponse request
	GetAdminKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminKeysResponse, error)

	// PostAdminKeysWithBodyWithResponse request with any body
	PostAdminKeysWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminKeysResponse, error)

	PostAdminKeysWithResponse(ctx context.Context, body PostAdminKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminKeysResponse, error)

	// DeleteAdminKeysKeyIdWithResponse request
	DeleteAdminKeysKeyIdWithResponse(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*DeleteAdminKeysKeyIdResponse, error)

	// GetAdminKeysKeyIdPublicWithResponse request
	GetAdminKeysKeyIdPublicWithResponse(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*GetAdminKeysKeyIdPublicResponse, error)

	// GetAdminTokensWithResponse request
	GetAdminTokensWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminTokensResponse, error)

	// PostAdminTokensWithBodyWithResponse request with any body
	PostAdminTokensWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminTokensResponse, error)

	PostAdminTokensWithResponse(ctx context.Context, body PostAdminTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminTokensResponse, error)

	// DeleteAdminTokensIdWithResponse request
	DeleteAdminTokensIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminTokensIdResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// GetPublicKeyWithResponse request
	GetPublicKeyWithResponse(ctx context.Context, params *GetPublicKeyParams, reqEditors ...RequestEditorFn) (*GetPublicKeyResponse, error)

	// PostSignWithBodyWithResponse request with any body
	PostSignWithBodyWithResponse(ctx context.Context, params *PostSignParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSignResponse, error)

	PostSignWithTextBodyWithResponse(ctx context.Context, params *PostSignParams, body PostSignTextRequestBody, reqEditors ...RequestEditorFn) (*PostSignResponse, error)
}

type GetAdminAuditResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AuditLogsResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAdminAuditResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminAuditResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdminAuditResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAdminKeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *KeyListResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAdminKeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminKeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdminKeysResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostAdminKeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *KeyResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostAdminKeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminKeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostAdminKeysResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteAdminKeysKeyIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *KeyDeletionResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteAdminKeysKeyIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAdminKeysKeyIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteAdminKeysKeyIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAdminKeysKeyIdPublicResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAdminKeysKeyIdPublicResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminKeysKeyIdPublicResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdminKeysKeyIdPublicResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAdminTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenListResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAdminTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdminTokensResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostAdminTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *TokenCreatedResponse
	JSON400      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostAdminTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostAdminTokensResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteAdminTokensIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenRevokeResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteAdminTokensIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAdminTokensIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteAdminTokensIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON503      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPublicKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetPublicKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPublicKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPublicKeyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostSignResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON429      *RateLimitError
	JSON500      *ErrorResponse
	JSON503      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostSignResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSignResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostSignResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetAdminAuditWithResponse request returning *GetAdminAuditResponse
func (c *ClientWithResponses) GetAdminAuditWithResponse(ctx context.Context, params *GetAdminAuditParams, reqEditors ...RequestEditorFn) (*GetAdminAuditResponse, error) {
	rsp, err := c.GetAdminAudit(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminAuditResponse(rsp)
}

// GetAdminKeysWithResponse request returning *GetAdminKeysResponse
func (c *ClientWithResponses) GetAdminKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminKeysResponse, error) {
	rsp, err := c.GetAdminKeys(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminKeysResponse(rsp)
}

// PostAdminKeysWithBodyWithResponse request with arbitrary body returning *PostAdminKeysResponse
func (c *ClientWithResponses) PostAdminKeysWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminKeysResponse, error) {
	rsp, err := c.PostAdminKeysWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminKeysResponse(rsp)
}

func (c *ClientWithResponses) PostAdminKeysWithResponse(ctx context.Context, body PostAdminKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminKeysResponse, error) {
	rsp, err := c.PostAdminKeys(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminKeysResponse(rsp)
}

// DeleteAdminKeysKeyIdWithResponse request returning *DeleteAdminKeysKeyIdResponse
func (c *ClientWithResponses) DeleteAdminKeysKeyIdWithResponse(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*DeleteAdminKeysKeyIdResponse, error) {
	rsp, err := c.DeleteAdminKeysKeyId(ctx, keyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAdminKeysKeyIdResponse(rsp)
}

// GetAdminKeysKeyIdPublicWithResponse request returning *GetAdminKeysKeyIdPublicResponse
func (c *ClientWithResponses) GetAdminKeysKeyIdPublicWithResponse(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*GetAdminKeysKeyIdPublicResponse, error) {
	rsp, err := c.GetAdminKeysKeyIdPublic(ctx, keyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminKeysKeyIdPublicResponse(rsp)
}

// GetAdminTokensWithResponse request returning *GetAdminTokensResponse
func (c *ClientWithResponses) GetAdminTokensWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminTokensResponse, error) {
	rsp, err := c.GetAdminTokens(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminTokensResponse(rsp)
}

// PostAdminTokensWithBodyWithResponse request with arbitrary body returning *PostAdminTokensResponse
func (c *ClientWithResponses) PostAdminTokensWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminTokensResponse, error) {
	rsp, err := c.PostAdminTokensWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminTokensResponse(rsp)
}

func (c *ClientWithResponses) PostAdminTokensWithResponse(ctx context.Context, body PostAdminTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminTokensResponse, error) {
	rsp, err := c.PostAdminTokens(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminTokensResponse(rsp)
}

// DeleteAdminTokensIdWithResponse request returning *DeleteAdminTokensIdResponse
func (c *ClientWithResponses) DeleteAdminTokensIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminTokensIdResponse, error) {
	rsp, err := c.DeleteAdminTokensId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAdminTokensIdResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// GetPublicKeyWithResponse request returning *GetPublicKeyResponse
func (c *ClientWithResponses) GetPublicKeyWithResponse(ctx context.Context, params *GetPublicKeyParams, reqEditors ...RequestEditorFn) (*GetPublicKeyResponse, error) {
	rsp, err := c.GetPublicKey(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPublicKeyResponse(rsp)
}

// PostSignWithBodyWithResponse request with arbitrary body returning *PostSignResponse
func (c *ClientWithResponses) PostSignWithBodyWithResponse(ctx context.Context, params *PostSignParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSignResponse, error) {
	rsp, err := c.PostSignWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSignResponse(rsp)
}

func (c *ClientWithResponses) PostSignWithTextBodyWithResponse(ctx context.Context, params *PostSignParams, body PostSignTextRequestBody, reqEditors ...RequestEditorFn) (*PostSignResponse, error) {
	rsp, err := c.PostSignWithTextBody(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSignResponse(rsp)
}

// ParseGetAdminAuditResponse parses an HTTP response from a GetAdminAuditWithResponse call
func ParseGetAdminAuditResponse(rsp *http.Response) (*GetAdminAuditResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminAuditResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AuditLogsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAdminKeysResponse parses an HTTP response from a GetAdminKeysWithResponse call
func ParseGetAdminKeysResponse(rsp *http.Response) (*GetAdminKeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminKeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest KeyListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostAdminKeysResponse parses an HTTP response from a PostAdminKeysWithResponse call
func ParsePostAdminKeysResponse(rsp *http.Response) (*PostAdminKeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAdminKeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest KeyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteAdminKeysKeyIdResponse parses an HTTP response from a DeleteAdminKeysKeyIdWithResponse call
func ParseDeleteAdminKeysKeyIdResponse(rsp *http.Response) (*DeleteAdminKeysKeyIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAdminKeysKeyIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest KeyDeletionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAdminKeysKeyIdPublicResponse parses an HTTP response from a GetAdminKeysKeyIdPublicWithResponse call
func ParseGetAdminKeysKeyIdPublicResponse(rsp *http.Response) (*GetAdminKeysKeyIdPublicResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminKeysKeyIdPublicResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAdminTokensResponse parses an HTTP response from a GetAdminTokensWithResponse call
func ParseGetAdminTokensResponse(rsp *http.Response) (*GetAdminTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostAdminTokensResponse parses an HTTP response from a PostAdminTokensWithResponse call
func ParsePostAdminTokensResponse(rsp *http.Response) (*PostAdminTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAdminTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest TokenCreatedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteAdminTokensIdResponse parses an HTTP response from a DeleteAdminTokensIdWithResponse call
func ParseDeleteAdminTokensIdResponse(rsp *http.Response) (*DeleteAdminTokensIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAdminTokensIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenRevokeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetPublicKeyResponse parses an HTTP response from a GetPublicKeyWithResponse call
func ParseGetPublicKeyResponse(rsp *http.Response) (*GetPublicKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPublicKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostSignResponse parses an HTTP response from a PostSignWithResponse call
func ParsePostSignResponse(rsp *http.Response) (*PostSignResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSignResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest RateLimitError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fpvd9o60v8qOn766j4mQJKmLX1FEkrZ0IQFsrt3m2yOsAfQjS35SjKNN4fvvkeSbWz8B9KTps05N2+C",
	"bVkzmvnNzE9jPVoO8wNGgUphdR4t4SzBx/pnN3SJ7DqSMKougYa+1flqCbKglm3dQ3QXBh7DbnzBmcQS",
	"LNuS7B7oncMhe8lhxe7BurUtGQVgdSwhOaELa20bOUO2EGMQAaMClLSAswC4JKBVcVhIpfrhE0p8pUcr",
	"nYhQCQvgaiaPLfRwIsEXxVlwupY3HOZWx/q/5mbxzXjlzeyy17YFnDN+xlzY9V4vHbi2LeKq4XPGfSyt",
	"jhWGRJmpsHQiRAg8XtgQ6EIurU67ZOA9RAN3j3E+SOxiidXQwkMOf4Yg5GA/3UQ4+wMcuYdQEToOCJGR",
	"OWPMA6ztJ4kPQmI/yAl1sYSGelSUHCtKOLgKbka5dJLsKuzEo6khN1onJttot4EeM0PW6Q3MOY4KkjWa",
	"7Bh7ZW/3stBIwqN7Pf1892UwmQwu+5ZtLgeX/+gOB+eWbV30fr+7vJrefbq6vkyuR+Ors54ef9cbj6/G",
	"8e3hYDLN3bgeDa+657lb571hb9pLb00G/cv0Ytyd9u6Ggy+DacmtnhIeq3U37v39ujeZam3PM8Ozig4u",
	"p73xZXcYPyyLY22Ouhh+YgzpyNsDfk+B9ZaLjQjb6Fbm4s+APbmsWdQSnPuSVKNicIbNG8WYuIdoIhnH",
	"i9LnWzpmBtubecuUFRLLUOyysVnSxIz9ngC1rRVwEWfSAEsJnFod6z83N+7/39wcZP692emAWOV8hCfT",
	"24l5qz0zSZecxN9S34+UrWDBsQtuKVgvIDoHD1T6qPauq0aAW+7Emqy3vch4pJ1OWLagC4iGRMiBBL+k",
	"dHkLxolc+qWJ3dRatytLn84JXQAPOKHlz9PaUu+qJJ9mp8uKtjNK1qyv2tr3EOWrdx2Ks9balcj1xBUq",
	"VatTb/Ito/r4IUlRxy07m7HUZSZIvnYbn3Bj3mp8uH08bq3fWLXFfjNr+yQ3q7qsmLV9Uj5rbZUOBfDv",
	"B8HGVOlMFea+NoyxaGzuMw7uiJMVlnAB0fbyW61W3q7tVuuFTLdlgqKqidiyNY/CmUecLaDBA/YDTw1s",
	"qL/TXn9wiUb9ERpdnw4HZ+ii9zs6HV6dXejHN/Tg4KDMo2MsYUh8IntJpXyxiit51J1LQ13hwfFCQVbw",
	"JSHnkodg13L1ujqcm7/MphOyoGNT9PPWlBwAHX6Yz9snzgenfQyHJ28PZ4eH8/ezd+9ns9Z7/Ba33n04",
	"ajnt43c3NMAcqETGujuWbGTu4ULFwbrT63Gv3ndTtSs6M3ukguPgISAcxICeY5MSffxgTHl08raVsWy7",
	"bBekwbi1D3paqshnU9ui2N8JJL2gSzVw27n67TI/ZmzgVufh2BimuNHQ8/BM2d1grLijcqtrXN4mhTEV",
	"c3+vFeKdr+ERwuEkMLtPa+Rh5a0HifSAj0gs2TeK4AE70osQo86euyKtUCImXaOdsVil1esrsZ5x/1qs",
	"Z5yEvo95tLMYx3NXanYZWzmTwE+Ot8Mzi2fc+G+38W+F583Pg7tm4/a3N5WBN9bdiGoDVKDoeygfcavX",
	"mtismLlrCd0vExEeFvJaJHru1OTJAWSaRvtNXxMgaWBkyerGiFk5uTUV/aYwAE7IiYwmSmHjrRlgDrwb",
	"KnAmV5+SjdTf/jnVxD+bAbquT6iJfjRnHDWxutH8DQF1A0aoVMpqi2iM6Qk3WF5KGSjrMOI6TxB6NTg/",
	"S2Ry5qM+kZ/DGTKdLoEYV3eGeIbOBvtIF8BXxAHtrwotFkLemfKX12RiXo2V8VUydNGKYDS6mkwTY8R5",
	"YqcmyieEzpkGMJG6JPdHfaQKNqELlAjrjgaZrWXHah+0DlrajAFQHBCrYx3pWzq7LLVjY1Vw6BINwQXI",
	"Yjofg+QEVoD0MOSxhUDfiFyiOfEkaHBqIRyrFxQ7tfogNQR0q1EL5NgHCVxYna+PFlHT/hkCjxIMdyxP",
	"8bzEGthoMcehJ2MmnPIRfZXyhXZCmyv5wtouF8jmcwEVErPyWnmiVxGlO8WlnbyNuEKAl7+56fg9/VWJ",
	"uTw3berNy/s1KctnBOp+33y3KguZcqShd9hqGQpPJZgtJg4CjzgaRM0/hOm+bITs7GjnGuw6arZyUope",
	"FRTHzyg+3xcsET2gK+wRF8WNPCX/7cvKV2QCe0jlNODI7EayyV6HZTbNf71VHhNJ/VYRnYl//W6cPJKu",
	"RmnuUDQMJT17XQqw5yEh1QYT6TerUseFefjDMLPdrSkxm1aezY2er9BnWn9l72QBARMlPjItC4SRqiqB",
	"2fWrV7S7hKkyBTeNmNjyk4b2KXOj53RR3E5Z59mPyrzrAjbazym4zjUXECHzZRBcFBPheeh50V+J5ekg",
	"TdFH4VuCNoW+7RTTfNQsd71pWxeRrBvegHAmwRSAa8ak0L2I+31lDEXRpE3lSzqDeRhm6+CmZdJtnx6e",
	"HZ0f995+Oum/+/z+hethWe+/AsdJw/4VIif1dg1amoFuT1bWJ1XW5BKQGZZmPYxEAA6Zx7f0l83qMqUx",
	"ZPqgvz6SgkXQSEp2NZ8s+MssD11AnOSOXw4qCqaUSTRnIXVfK3faACwL1U0fqpo9acKU3VCKj0iAw0Ei",
	"H6v9F/YQBaWaB3gFQuP5/LQSsdNk3/nD0k+xAVdi11iN10qr8h6pJlem+4sw8hhdNDyyAheZyTPtkbMB",
	"EpGQ4JuNNQslwhTpfoY593GApipJ5fuqiAjEQYacgptrrh5Us7WM85+fr2Vb/i/M2Eo77VWoizsyvwJb",
	"O259eDn5ZvGqCCHsccBuhOCBCPkqo/ALoVLV6WwcFlNr85HUU0bTKEc4DqlZhIj7EXFYMbNyFWTE98El",
	"OoypiwLgPlbrraOWJs72ZJakngzsOvFz+6NT+dbHhEpkxV3mFycIMa4TioB0l8HgO6PSawN4iswSiJsz",
	"QJW84WwJzr3mAWYgYnN9Fc9URg3MaaMfyQq2TpqVGC3pZBOBkkNO2m9HP0eH9HiVdlvqFzMH0ie3jDcM",
	"t1Os+qn7DLXfxTLkgFbA1XYDx03ign/SYxb7ddPTs6E/b0tR54fioZG/thx7JY/aPYU+uN55rGCiE7Kg",
	"aEEkcpjvE4l0RzYUhC5MbjAtk/6oX9o2UQxyYg7G/3j4Jd8eloBd/UEsnvZfjfhUTEPvyJ9YIqsIr2LU",
	"Tc2t9/dh9oTOXlS39WxCawKmP9JfBXVGeXF2e4pdNM4y26OfwQCw57Fv4CLJUCgAySURJkB+dgY5Pnw+",
	"pr91Lq5EvBqB9CdVBA8OgPszOdDEpLFY2eet6Du1SAr6NcUrTMyn2wIP25w0+Hqrsk/x2/82O9PZNJNJ",
	"lej1/wIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
