// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes       bearerAuthContextKey       = "bearerAuth.Scopes"
	OidcAuthScopes         oidcAuthContextKey         = "oidcAuth.Scopes"
	ServiceTokenAuthScopes serviceTokenAuthContextKey = "serviceTokenAuth.Scopes"
)

// Defines values for AuditAction.
const (
	AuditActionKeyRotate     AuditAction = "key_rotate"
	AuditActionKeyUpload     AuditAction = "key_upload"
	AuditActionSign          AuditAction = "sign"
	AuditActionSubjectCreate AuditAction = "subject_create"
	AuditActionSubjectRevoke AuditAction = "subject_revoke"
	AuditActionTokenCreate   AuditAction = "token_create"
	AuditActionTokenRevoke   AuditAction = "token_revoke"
)

// Valid indicates whether the value is a known member of the AuditAction enum.
func (e AuditAction) Valid() bool {
	switch e {
	case AuditActionKeyRotate:
		return true
	case AuditActionKeyUpload:
		return true
	case AuditActionSign:
		return true
	case AuditActionSubjectCreate:
		return true
	case AuditActionSubjectRevoke:
		return true
	case AuditActionTokenCreate:
		return true
	case AuditActionTokenRevoke:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	AUDITERROR         ErrorCode = "AUDIT_ERROR"
	AUTHINVALID        ErrorCode = "AUTH_INVALID"
	AUTHMISSING        ErrorCode = "AUTH_MISSING"
	INTERNALERROR      ErrorCode = "INTERNAL_ERROR"
	INVALIDREQUEST     ErrorCode = "INVALID_REQUEST"
	KEYDELETEERROR     ErrorCode = "KEY_DELETE_ERROR"
	KEYLISTERROR       ErrorCode = "KEY_LIST_ERROR"
	KEYNOTFOUND        ErrorCode = "KEY_NOT_FOUND"
	KEYPROCESSINGERROR ErrorCode = "KEY_PROCESSING_ERROR"
	KEYUPLOADERROR     ErrorCode = "KEY_UPLOAD_ERROR"
	NOTFOUND           ErrorCode = "NOT_FOUND"
	RATELIMITED        ErrorCode = "RATE_LIMITED"
	RATELIMITERROR     ErrorCode = "RATE_LIMIT_ERROR"
	SIGNERROR          ErrorCode = "SIGN_ERROR"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case AUDITERROR:
		return true
	case AUTHINVALID:
		return true
	case AUTHMISSING:
		return true
	case INTERNALERROR:
		return true
	case INVALIDREQUEST:
		return true
	case KEYDELETEERROR:
		return true
	case KEYLISTERROR:
		return true
	case KEYNOTFOUND:
		return true
	case KEYPROCESSINGERROR:
		return true
	case KEYUPLOADERROR:
		return true
	case NOTFOUND:
		return true
	case RATELIMITED:
		return true
	case RATELIMITERROR:
		return true
	case SIGNERROR:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Healthy  HealthStatus = "healthy"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Healthy:
		return true
	default:
		return false
	}
}

// AuditAction defines model for AuditAction.
type AuditAction string

// AuditLogsResponse defines model for AuditLogsResponse.
type AuditLogsResponse struct {
	Count int `json:"count"`
	Logs  []struct {
		Action    AuditAction        `json:"action"`
		ErrorCode *ErrorCode         `json:"errorCode,omitempty"`
		Id        openapi_types.UUID `json:"id"`
		Issuer    string             `json:"issuer"`
		KeyId     string             `json:"keyId"`
		Metadata  *string            `json:"metadata,omitempty"`
		RequestId openapi_types.UUID `json:"requestId"`
		Subject   string             `json:"subject"`
		Success   bool               `json:"success"`
		Timestamp time.Time          `json:"timestamp"`
	} `json:"logs"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      ErrorCode           `json:"code"`
	Error     string              `json:"error"`
	RequestId *openapi_types.UUID `json:"requestId,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Checks struct {
		Database   bool `json:"database"`
		KeyStorage bool `json:"keyStorage"`
	} `json:"checks"`
	Status    HealthStatus `json:"status"`
	Timestamp time.Time    `json:"timestamp"`
	Version   string       `json:"version"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus string

// KeyDeletionResponse defines model for KeyDeletionResponse.
type KeyDeletionResponse struct {
	Deleted bool `json:"deleted"`
	Success bool `json:"success"`
}

// KeyListItem defines model for KeyListItem.
type KeyListItem struct {
	Algorithm   string `json:"algorithm"`
	CreatedAt   string `json:"createdAt"`
	Fingerprint string `json:"fingerprint"`
	KeyId       string `json:"keyId"`
}

// KeyListResponse defines model for KeyListResponse.
type KeyListResponse struct {
	Keys []KeyListItem `json:"keys"`
}

// KeyResponse defines model for KeyResponse.
type KeyResponse struct {
	Algorithm   string `json:"algorithm"`
	Fingerprint string `json:"fingerprint"`
	KeyId       string `json:"keyId"`
	Success     *bool  `json:"success,omitempty"`
	UserId      string `json:"userId"`
}

// KeyUpload defines model for KeyUpload.
type KeyUpload struct {
	ArmoredPrivateKey string `json:"armoredPrivateKey"`
	KeyId             string `json:"keyId"`
}

// PublicKeyResponse defines model for PublicKeyResponse.
type PublicKeyResponse = string

// RateLimitError defines model for RateLimitError.
type RateLimitError struct {
	Code       ErrorCode `json:"code"`
	Error      string    `json:"error"`
	RetryAfter int       `json:"retryAfter"`
}

// SignRequest defines model for SignRequest.
type SignRequest = string

// SignResponse defines model for SignResponse.
type SignResponse = string

// SubjectCreate defines model for SubjectCreate.
type SubjectCreate struct {
	ExpiresInDays *int          `json:"expiresInDays,omitempty"`
	Issuer        string        `json:"issuer"`
	KeyIds        *[]string     `json:"keyIds,omitempty"`
	Name          SubjectName   `json:"name"`
	SubjectPrefix SubjectPrefix `json:"subjectPrefix"`
}

// SubjectCreatedResponse defines model for SubjectCreatedResponse.
type SubjectCreatedResponse struct {
	CreatedAt     string        `json:"createdAt"`
	ExpiresAt     *string       `json:"expiresAt"`
	Id            string        `json:"id"`
	Issuer        string        `json:"issuer"`
	KeyIds        *[]string     `json:"keyIds"`
	LastUsedAt    *string       `json:"lastUsedAt"`
	Name          SubjectName   `json:"name"`
	RevokedAt     *string       `json:"revokedAt"`
	SubjectPrefix SubjectPrefix `json:"subjectPrefix"`
}

// SubjectListResponse defines model for SubjectListResponse.
type SubjectListResponse struct {
	Subjects []SubjectSummary `json:"subjects"`
}

// SubjectName defines model for SubjectName.
type SubjectName = string

// SubjectPrefix defines model for SubjectPrefix.
type SubjectPrefix = string

// SubjectRevokeResponse defines model for SubjectRevokeResponse.
type SubjectRevokeResponse struct {
	Id      string `json:"id"`
	Success bool   `json:"success"`
}

// SubjectSummary defines model for SubjectSummary.
type SubjectSummary struct {
	CreatedAt     string        `json:"createdAt"`
	ExpiresAt     *string       `json:"expiresAt"`
	Id            string        `json:"id"`
	Issuer        string        `json:"issuer"`
	KeyIds        *[]string     `json:"keyIds"`
	LastUsedAt    *string       `json:"lastUsedAt"`
	Name          SubjectName   `json:"name"`
	RevokedAt     *string       `json:"revokedAt"`
	SubjectPrefix SubjectPrefix `json:"subjectPrefix"`
}

// TokenCreate defines model for TokenCreate.
type TokenCreate struct {
	ExpiresInDays *int      `json:"expiresInDays,omitempty"`
	KeyIds        *[]string `json:"keyIds,omitempty"`
	Name          TokenName `json:"name"`
}

// TokenCreatedResponse defines model for TokenCreatedResponse.
type TokenCreatedResponse struct {
	ExpiresAt *string   `json:"expiresAt"`
	Id        string    `json:"id"`
	KeyIds    *[]string `json:"keyIds"`
	Name      TokenName `json:"name"`

	// Token Plaintext token; shown exactly once
	Token string `json:"token"`
}

// TokenListResponse defines model for TokenListResponse.
type TokenListResponse struct {
	Tokens []TokenSummary `json:"tokens"`
}

// TokenName defines model for TokenName.
type TokenName = string

// TokenRevokeResponse defines model for TokenRevokeResponse.
type TokenRevokeResponse struct {
	Id      string `json:"id"`
	Success bool   `json:"success"`
}

// TokenSummary defines model for TokenSummary.
type TokenSummary struct {
	CreatedAt  string    `json:"createdAt"`
	ExpiresAt  *string   `json:"expiresAt"`
	Id         string    `json:"id"`
	KeyIds     *[]string `json:"keyIds"`
	LastUsedAt *string   `json:"lastUsedAt"`
	Name       TokenName `json:"name"`
	RevokedAt  *string   `json:"revokedAt"`
}

// X509KeyResponse defines model for X509KeyResponse.
type X509KeyResponse struct {
	Algorithm   string `json:"algorithm"`
	Fingerprint string `json:"fingerprint"`
	KeyId       string `json:"keyId"`
	Subject     string `json:"subject"`
	Success     bool   `json:"success"`
}

// X509KeyUpload defines model for X509KeyUpload.
type X509KeyUpload struct {
	CertificatePem string  `json:"certificatePem"`
	ChainPem       *string `json:"chainPem,omitempty"`
	KeyId          string  `json:"keyId"`
	PrivateKeyPem  string  `json:"privateKeyPem"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// oidcAuthContextKey is the context key for oidcAuth security scheme
type oidcAuthContextKey string

// serviceTokenAuthContextKey is the context key for serviceTokenAuth security scheme
type serviceTokenAuthContextKey string

// GetAdminAuditParams defines parameters for GetAdminAudit.
type GetAdminAuditParams struct {
	Limit     *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset    *int       `form:"offset,omitempty" json:"offset,omitempty"`
	Action    *string    `form:"action,omitempty" json:"action,omitempty"`
	Subject   *string    `form:"subject,omitempty" json:"subject,omitempty"`
	StartDate *time.Time `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate   *time.Time `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// GetPublicKeyParams defines parameters for GetPublicKey.
type GetPublicKeyParams struct {
	KeyId *string `form:"keyId,omitempty" json:"keyId,omitempty"`
}

// PostSignParams defines parameters for PostSign.
type PostSignParams struct {
	KeyId      *string             `form:"keyId,omitempty" json:"keyId,omitempty"`
	XRequestID *openapi_types.UUID `json:"X-Request-ID,omitempty"`
}

// PostAdminKeysJSONRequestBody defines body for PostAdminKeys for application/json ContentType.
type PostAdminKeysJSONRequestBody = KeyUpload

// PostAdminKeysX509JSONRequestBody defines body for PostAdminKeysX509 for application/json ContentType.
type PostAdminKeysX509JSONRequestBody = X509KeyUpload

// PostAdminSubjectsJSONRequestBody defines body for PostAdminSubjects for application/json ContentType.
type PostAdminSubjectsJSONRequestBody = SubjectCreate

// PostAdminTokensJSONRequestBody defines body for PostAdminTokens for application/json ContentType.
type PostAdminTokensJSONRequestBody = TokenCreate

// PostSignTextRequestBody defines body for PostSign for text/plain ContentType.
type PostSignTextRequestBody = SignRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAdminAudit request
	GetAdminAudit(ctx context.Context, params *GetAdminAuditParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminKeys request
	GetAdminKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminKeysWithBody request with any body
	PostAdminKeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAdminKeys(ctx context.Context, body PostAdminKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminKeysX509WithBody request with any body
	PostAdminKeysX509WithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAdminKeysX509(ctx context.Context, body PostAdminKeysX509JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAdminKeysKeyId request
	DeleteAdminKeysKeyId(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminKeysKeyIdPublic request
	GetAdminKeysKeyIdPublic(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminSubjects request
	GetAdminSubjects(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminSubjectsWithBody request with any body
	PostAdminSubjectsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAdminSubjects(ctx context.Context, body PostAdminSubjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAdminSubjectsId request
	DeleteAdminSubjectsId(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminTokens request
	GetAdminTokens(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminTokensWithBody request with any body
	PostAdminTokensWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAdminTokens(ctx context.Context, body PostAdminTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAdminTokensId request
	DeleteAdminTokensId(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPublicKey request
	GetPublicKey(ctx context.Context, params *GetPublicKeyParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSignWithBody request with any body
	PostSignWithBody(ctx context.Context, params *PostSignParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSignWithTextBody(ctx context.Context, params *PostSignParams, body PostSignTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAdminAudit(ctx context.Context, params *GetAdminAuditParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminAuditRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminKeysRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminKeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminKeysRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminKeys(ctx context.Context, body PostAdminKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminKeysRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminKeysX509WithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminKeysX509RequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminKeysX509(ctx context.Context, body PostAdminKeysX509JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminKeysX509Request(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAdminKeysKeyId(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAdminKeysKeyIdRequest(c.Server, keyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminKeysKeyIdPublic(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminKeysKeyIdPublicRequest(c.Server, keyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminSubjects(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminSubjectsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminSubjectsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminSubjectsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminSubjects(ctx context.Context, body PostAdminSubjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminSubjectsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAdminSubjectsId(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAdminSubjectsIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminTokens(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminTokensRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminTokensWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminTokensRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminTokens(ctx context.Context, body PostAdminTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminTokensRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAdminTokensId(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAdminTokensIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPublicKey(ctx context.Context, params *GetPublicKeyParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPublicKeyRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSignWithBody(ctx context.Context, params *PostSignParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSignRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSignWithTextBody(ctx context.Context, params *PostSignParams, body PostSignTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSignRequestWithTextBody(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAdminAuditRequest generates requests for GetAdminAudit
func NewGetAdminAuditRequest(server string, params *GetAdminAuditParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/audit")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Action != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "action", *params.Action, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Subject != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "subject", *params.Subject, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.StartDate != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "startDate", *params.StartDate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.EndDate != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "endDate", *params.EndDate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminKeysRequest generates requests for GetAdminKeys
func NewGetAdminKeysRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAdminKeysRequest calls the generic PostAdminKeys builder with application/json body
func NewPostAdminKeysRequest(server string, body PostAdminKeysJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAdminKeysRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAdminKeysRequestWithBody generates requests for PostAdminKeys with any type of body
func NewPostAdminKeysRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAdminKeysX509Request calls the generic PostAdminKeysX509 builder with application/json body
func NewPostAdminKeysX509Request(server string, body PostAdminKeysX509JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAdminKeysX509RequestWithBody(server, "application/json", bodyReader)
}

// NewPostAdminKeysX509RequestWithBody generates requests for PostAdminKeysX509 with any type of body
func NewPostAdminKeysX509RequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys/x509")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAdminKeysKeyIdRequest generates requests for DeleteAdminKeysKeyId
func NewDeleteAdminKeysKeyIdRequest(server string, keyId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "keyId", keyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminKeysKeyIdPublicRequest generates requests for GetAdminKeysKeyIdPublic
func NewGetAdminKeysKeyIdPublicRequest(server string, keyId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "keyId", keyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys/%s/public", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminSubjectsRequest generates requests for GetAdminSubjects
func NewGetAdminSubjectsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/subjects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAdminSubjectsRequest calls the generic PostAdminSubjects builder with application/json body
func NewPostAdminSubjectsRequest(server string, body PostAdminSubjectsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAdminSubjectsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAdminSubjectsRequestWithBody generates requests for PostAdminSubjects with any type of body
func NewPostAdminSubjectsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/subjects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAdminSubjectsIdRequest generates requests for DeleteAdminSubjectsId
func NewDeleteAdminSubjectsIdRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/subjects/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminTokensRequest generates requests for GetAdminTokens
func NewGetAdminTokensRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/tokens")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAdminTokensRequest calls the generic PostAdminTokens builder with application/json body
func NewPostAdminTokensRequest(server string, body PostAdminTokensJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAdminTokensRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAdminTokensRequestWithBody generates requests for PostAdminTokens with any type of body
func NewPostAdminTokensRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/tokens")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAdminTokensIdRequest generates requests for DeleteAdminTokensId
func NewDeleteAdminTokensIdRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/tokens/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPublicKeyRequest generates requests for GetPublicKey
func NewGetPublicKeyRequest(server string, params *GetPublicKeyParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/public-key")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.KeyId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "keyId", *params.KeyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostSignRequestWithTextBody calls the generic PostSign builder with text/plain body
func NewPostSignRequestWithTextBody(server string, params *PostSignParams, body PostSignTextRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	if stringer, ok := interface{}(body).(fmt.Stringer); ok {
		bodyReader = strings.NewReader(stringer.String())
	} else {
		bodyReader = strings.NewReader(fmt.Sprint(body))
	}
	return NewPostSignRequestWithBody(server, params, "text/plain", bodyReader)
}

// NewPostSignRequestWithBody generates requests for PostSign with any type of body
func NewPostSignRequestWithBody(server string, params *PostSignParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sign")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.KeyId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "keyId", *params.KeyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XRequestID != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", *params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Request-ID", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAdminAuditWithResponse request
	GetAdminAuditWithResponse(ctx context.Context, params *GetAdminAuditParams, reqEditors ...RequestEditorFn) (*GetAdminAuditResponse, error)

	// GetAdminKeysWithResponse request
	GetAdminKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminKeysResponse, error)

	// PostAdminKeysWithBodyWithResponse request with any body
	PostAdminKeysWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminKeysResponse, error)

	PostAdminKeysWithResponse(ctx context.Context, body PostAdminKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminKeysResponse, error)

	// PostAdminKeysX509WithBodyWithResponse request with any body
	PostAdminKeysX509WithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminKeysX509Response, error)

	PostAdminKeysX509WithResponse(ctx context.Context, body PostAdminKeysX509JSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminKeysX509Response, error)

	// DeleteAdminKeysKeyIdWithResponse request
	DeleteAdminKeysKeyIdWithResponse(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*DeleteAdminKeysKeyIdResponse, error)

	// GetAdminKeysKeyIdPublicWithResponse request
	GetAdminKeysKeyIdPublicWithResponse(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*GetAdminKeysKeyIdPublicResponse, error)

	// GetAdminSubjectsWithResponse request
	GetAdminSubjectsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminSubjectsResponse, error)

	// PostAdminSubjectsWithBodyWithResponse request with any body
	PostAdminSubjectsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminSubjectsResponse, error)

	PostAdminSubjectsWithResponse(ctx context.Context, body PostAdminSubjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminSubjectsResponse, error)

	// DeleteAdminSubjectsIdWithResponse request
	DeleteAdminSubjectsIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminSubjectsIdResponse, error)

	// GetAdminTokensWithResponse request
	GetAdminTokensWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminTokensResponse, error)

	// PostAdminTokensWithBodyWithResponse request with any body
	PostAdminTokensWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminTokensResponse, error)

	PostAdminTokensWithResponse(ctx context.Context, body PostAdminTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminTokensResponse, error)

	// DeleteAdminTokensIdWithResponse request
	DeleteAdminTokensIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminTokensIdResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// GetPublicKeyWithResponse request
	GetPublicKeyWithResponse(ctx context.Context, params *GetPublicKeyParams, reqEditors ...RequestEditorFn) (*GetPublicKeyResponse, error)

	// PostSignWithBodyWithResponse request with any body
	PostSignWithBodyWithResponse(ctx context.Context, params *PostSignParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSignResponse, error)

	PostSignWithTextBodyWithResponse(ctx context.Context, params *PostSignParams, body PostSignTextRequestBody, reqEditors ...RequestEditorFn) (*PostSignResponse, error)
}

type GetAdminAuditResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AuditLogsResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAdminAuditResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminAuditResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdminAuditResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAdminKeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *KeyListResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAdminKeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminKeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdminKeysResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostAdminKeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *KeyResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostAdminKeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminKeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostAdminKeysResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostAdminKeysX509Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *X509KeyResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostAdminKeysX509Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminKeysX509Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostAdminKeysX509Response) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteAdminKeysKeyIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *KeyDeletionResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteAdminKeysKeyIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAdminKeysKeyIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteAdminKeysKeyIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAdminKeysKeyIdPublicResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAdminKeysKeyIdPublicResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminKeysKeyIdPublicResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdminKeysKeyIdPublicResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAdminSubjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SubjectListResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAdminSubjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminSubjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdminSubjectsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostAdminSubjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *SubjectCreatedResponse
	JSON400      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostAdminSubjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminSubjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostAdminSubjectsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteAdminSubjectsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SubjectRevokeResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteAdminSubjectsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAdminSubjectsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteAdminSubjectsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAdminTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenListResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAdminTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdminTokensResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostAdminTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *TokenCreatedResponse
	JSON400      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostAdminTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostAdminTokensResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteAdminTokensIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenRevokeResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteAdminTokensIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAdminTokensIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteAdminTokensIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON503      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPublicKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetPublicKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPublicKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPublicKeyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostSignResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON429      *RateLimitError
	JSON500      *ErrorResponse
	JSON503      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostSignResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSignResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostSignResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetAdminAuditWithResponse request returning *GetAdminAuditResponse
func (c *ClientWithResponses) GetAdminAuditWithResponse(ctx context.Context, params *GetAdminAuditParams, reqEditors ...RequestEditorFn) (*GetAdminAuditResponse, error) {
	rsp, err := c.GetAdminAudit(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminAuditResponse(rsp)
}

// GetAdminKeysWithResponse request returning *GetAdminKeysResponse
func (c *ClientWithResponses) GetAdminKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminKeysResponse, error) {
	rsp, err := c.GetAdminKeys(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminKeysResponse(rsp)
}

// PostAdminKeysWithBodyWithResponse request with arbitrary body returning *PostAdminKeysResponse
func (c *ClientWithResponses) PostAdminKeysWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminKeysResponse, error) {
	rsp, err := c.PostAdminKeysWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminKeysResponse(rsp)
}

func (c *ClientWithResponses) PostAdminKeysWithResponse(ctx context.Context, body PostAdminKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminKeysResponse, error) {
	rsp, err := c.PostAdminKeys(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminKeysResponse(rsp)
}

// PostAdminKeysX509WithBodyWithResponse request with arbitrary body returning *PostAdminKeysX509Response
func (c *ClientWithResponses) PostAdminKeysX509WithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminKeysX509Response, error) {
	rsp, err := c.PostAdminKeysX509WithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminKeysX509Response(rsp)
}

func (c *ClientWithResponses) PostAdminKeysX509WithResponse(ctx context.Context, body PostAdminKeysX509JSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminKeysX509Response, error) {
	rsp, err := c.PostAdminKeysX509(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminKeysX509Response(rsp)
}

// DeleteAdminKeysKeyIdWithResponse request returning *DeleteAdminKeysKeyIdResponse
func (c *ClientWithResponses) DeleteAdminKeysKeyIdWithResponse(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*DeleteAdminKeysKeyIdResponse, error) {
	rsp, err := c.DeleteAdminKeysKeyId(ctx, keyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAdminKeysKeyIdResponse(rsp)
}

// GetAdminKeysKeyIdPublicWithResponse request returning *GetAdminKeysKeyIdPublicResponse
func (c *ClientWithResponses) GetAdminKeysKeyIdPublicWithResponse(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*GetAdminKeysKeyIdPublicResponse, error) {
	rsp, err := c.GetAdminKeysKeyIdPublic(ctx, keyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminKeysKeyIdPublicResponse(rsp)
}

// GetAdminSubjectsWithResponse request returning *GetAdminSubjectsResponse
func (c *ClientWithResponses) GetAdminSubjectsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminSubjectsResponse, error) {
	rsp, err := c.GetAdminSubjects(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminSubjectsResponse(rsp)
}

// PostAdminSubjectsWithBodyWithResponse request with arbitrary body returning *PostAdminSubjectsResponse
func (c *ClientWithResponses) PostAdminSubjectsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminSubjectsResponse, error) {
	rsp, err := c.PostAdminSubjectsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminSubjectsResponse(rsp)
}

func (c *ClientWithResponses) PostAdminSubjectsWithResponse(ctx context.Context, body PostAdminSubjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminSubjectsResponse, error) {
	rsp, err := c.PostAdminSubjects(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminSubjectsResponse(rsp)
}

// DeleteAdminSubjectsIdWithResponse request returning *DeleteAdminSubjectsIdResponse
func (c *ClientWithResponses) DeleteAdminSubjectsIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminSubjectsIdResponse, error) {
	rsp, err := c.DeleteAdminSubjectsId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAdminSubjectsIdResponse(rsp)
}

// GetAdminTokensWithResponse request returning *GetAdminTokensResponse
func (c *ClientWithResponses) GetAdminTokensWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminTokensResponse, error) {
	rsp, err := c.GetAdminTokens(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminTokensResponse(rsp)
}

// PostAdminTokensWithBodyWithResponse request with arbitrary body returning *PostAdminTokensResponse
func (c *ClientWithResponses) PostAdminTokensWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminTokensResponse, error) {
	rsp, err := c.PostAdminTokensWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminTokensResponse(rsp)
}

func (c *ClientWithResponses) PostAdminTokensWithResponse(ctx context.Context, body PostAdminTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminTokensResponse, error) {
	rsp, err := c.PostAdminTokens(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminTokensResponse(rsp)
}

// DeleteAdminTokensIdWithResponse request returning *DeleteAdminTokensIdResponse
func (c *ClientWithResponses) DeleteAdminTokensIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminTokensIdResponse, error) {
	rsp, err := c.DeleteAdminTokensId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAdminTokensIdResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// GetPublicKeyWithResponse request returning *GetPublicKeyResponse
func (c *ClientWithResponses) GetPublicKeyWithResponse(ctx context.Context, params *GetPublicKeyParams, reqEditors ...RequestEditorFn) (*GetPublicKeyResponse, error) {
	rsp, err := c.GetPublicKey(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPublicKeyResponse(rsp)
}

// PostSignWithBodyWithResponse request with arbitrary body returning *PostSignResponse
func (c *ClientWithResponses) PostSignWithBodyWithResponse(ctx context.Context, params *PostSignParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSignResponse, error) {
	rsp, err := c.PostSignWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSignResponse(rsp)
}

func (c *ClientWithResponses) PostSignWithTextBodyWithResponse(ctx context.Context, params *PostSignParams, body PostSignTextRequestBody, reqEditors ...RequestEditorFn) (*PostSignResponse, error) {
	rsp, err := c.PostSignWithTextBody(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSignResponse(rsp)
}

// ParseGetAdminAuditResponse parses an HTTP response from a GetAdminAuditWithResponse call
func ParseGetAdminAuditResponse(rsp *http.Response) (*GetAdminAuditResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminAuditResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AuditLogsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAdminKeysResponse parses an HTTP response from a GetAdminKeysWithResponse call
func ParseGetAdminKeysResponse(rsp *http.Response) (*GetAdminKeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminKeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest KeyListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostAdminKeysResponse parses an HTTP response from a PostAdminKeysWithResponse call
func ParsePostAdminKeysResponse(rsp *http.Response) (*PostAdminKeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAdminKeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest KeyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostAdminKeysX509Response parses an HTTP response from a PostAdminKeysX509WithResponse call
func ParsePostAdminKeysX509Response(rsp *http.Response) (*PostAdminKeysX509Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAdminKeysX509Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest X509KeyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteAdminKeysKeyIdResponse parses an HTTP response from a DeleteAdminKeysKeyIdWithResponse call
func ParseDeleteAdminKeysKeyIdResponse(rsp *http.Response) (*DeleteAdminKeysKeyIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAdminKeysKeyIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest KeyDeletionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAdminKeysKeyIdPublicResponse parses an HTTP response from a GetAdminKeysKeyIdPublicWithResponse call
func ParseGetAdminKeysKeyIdPublicResponse(rsp *http.Response) (*GetAdminKeysKeyIdPublicResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminKeysKeyIdPublicResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAdminSubjectsResponse parses an HTTP response from a GetAdminSubjectsWithResponse call
func ParseGetAdminSubjectsResponse(rsp *http.Response) (*GetAdminSubjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminSubjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SubjectListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostAdminSubjectsResponse parses an HTTP response from a PostAdminSubjectsWithResponse call
func ParsePostAdminSubjectsResponse(rsp *http.Response) (*PostAdminSubjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAdminSubjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest SubjectCreatedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteAdminSubjectsIdResponse parses an HTTP response from a DeleteAdminSubjectsIdWithResponse call
func ParseDeleteAdminSubjectsIdResponse(rsp *http.Response) (*DeleteAdminSubjectsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAdminSubjectsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SubjectRevokeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAdminTokensResponse parses an HTTP response from a GetAdminTokensWithResponse call
func ParseGetAdminTokensResponse(rsp *http.Response) (*GetAdminTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostAdminTokensResponse parses an HTTP response from a PostAdminTokensWithResponse call
func ParsePostAdminTokensResponse(rsp *http.Response) (*PostAdminTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAdminTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest TokenCreatedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteAdminTokensIdResponse parses an HTTP response from a DeleteAdminTokensIdWithResponse call
func ParseDeleteAdminTokensIdResponse(rsp *http.Response) (*DeleteAdminTokensIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAdminTokensIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenRevokeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetPublicKeyResponse parses an HTTP response from a GetPublicKeyWithResponse call
func ParseGetPublicKeyResponse(rsp *http.Response) (*GetPublicKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPublicKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostSignResponse parses an HTTP response from a PostSignWithResponse call
func ParsePostSignResponse(rsp *http.Response) (*PostSignResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSignResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest RateLimitError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fz9Uhs5En8V1Wz+2N2zwRAgga2rOgMO8eGAzzZ32QssJc+0bS0z0qykIcymqLqHuCe8J7mSNJ+eDxvK",
	"mLCb/BPPjKa71Z8/tTR8sWzm+YwClcI6+GIJewYe1j/bgUNk25aEUXUJNPCsg0+WIFNqNawbCK8D32XY",
	"iS44k1iC1bAkuwF6bXPIXnK4ZTfqUgTjX8GW6fP4RjTiqmHJ0AfrwBKSEzq17htGkh6bigEIn1EBSh6f",
	"Mx+4JKCFtVlApfrhEUo8JWkrIUSohClwRcllUz2cSPBEkQpOZvuKw8Q6sL7bTNWzGelmM6uY+4YFnDN+",
	"xBxY9F4nGXjfsIijhk8Y97C0DqwgIEqRhakTIQLg0cR6QKdyZh1slQy8gbDrLDHOA4kdLLEaWnjI4bcA",
	"hOwuJ1tkuSWYisC2QYgMzzFjLmCtP0k8EBJ7fo6pgyU01aMi50hQwsFRDmmES4hkZ9GILZooMpU6Vlkq",
	"Xep6zAy5T25gznFY4Ky9qRH5XtnbnaxrxAHUvhi9v/7QHQ67ZydWw1x2z/7Z7nWPrYZ12vn5+ux8dP3u",
	"/OIsvu4Pzo86evx1ZzA4H0S3e93hKHfjot87bx/nbh13ep1RJ7k17J6cJReD9qhz3et+6I5KbnUU80is",
	"60HnHxed4UhLe5wZnhW0ezbqDM7avehhWRxrddTF8ANjSEfeEu73ELeeM7Fh0TCylZn4PWBXzmomNQP7",
	"piTVqBgcY/NGMSZuIBxKxvG09PmcjJnBjZRumbBCYhmIRTo2UxqasY8J0IZ1C1xEmdTHUgKn1oH1y+Wl",
	"85fLy43Mf68WGiASOR/hMflGrN5qywyTKcfxN9P3Q6UrmHLsgFPqrKcQHoMLKn1UW9dRI8ApN2JN1puf",
	"ZDSykRAsm9AphD0iZFeCV1K63CnjRM680sRuqq3TlqVPJ4ROgfuc0PLnSW2pN1WcT7PksqwbGSFr5let",
	"7RsI89W7zouz2lqUyDXhCpGqxalX+ZxSPXwXp6idViObsdRlJkg+tZvvcHPSau5ffdlp3b+yaot9SnVr",
	"L0dVXVZQ3dorp1pbpQMB/PFOkKoqoVSh7guDKYvK5h7j4PQ5ucUSTiGcn36r1crrdavVWpPq5lRQFDVm",
	"WzbnfjB2iT3naHCHPd9VA5vq32HnpHuG+id91L847HWP0GnnZ3TYOz861Y8v6cbGRplFB1hCj3hEduJK",
	"ubaKK3nYnkgDXeHOdgNBbuFDDM4lD6BRi9Xr6nCOfplOh2RKB6bo57UpOQDa3p9MtvbsfXtrB7b3drfH",
	"29uTt+M3b8fj1lu8i1tv9l+37K2dN5fUxxyoREa7C6ZseC5hQoXB2qOLQafedkODU4/MOqlgOrjzCQfR",
	"pcfYJEUP3xllvt7bbWV0u1W2DkqXFSkc4qQy1eSz7kqTjkdo1xDemk/SDYtib6F/Rno6U0PTRUmfw4Tc",
	"LfluNHje5zT34sohGl3qd1mbOTWgsLYcR6Y1T2ngunis/MjETHGF6JQSSS28jEkLYyrYJpZxsZAXIp7C",
	"QiEfYUjTD1iWwQrNrlcF9bZPdJiHN6nhsuLnlFXjNfXYJxJgefwTUR0Gnod5uBACJfRrJDyLrJhJAHs7",
	"84kxG/+4+Xu7+W8V/+nPjevN5tWPr2pSXmrEDKPt3d0aTpeXwx8/Hfxt80r/+OXyUsQXdYwG2kbVOq8I",
	"rcfgeuLUKTY20rdE8S1R1CSKEbsB+jSA4Ksv83ruxuRlZXqBumpq8UqCaBWR8kAtRJ1104UQNie+6V1b",
	"fRcrw95JpAf8hMSMfaYI7rAt3RAxai/ZU41c27DJeHKqsUqt19cyTXH5SqYpLlvHItqVkj11DdNMnr+w",
	"5HT2HGXlK60duQB6SOWoCZBVpviPu639P1nTKdlEWkk8LO4/xRxr1F/VhLLVzwmxsYS+acI+ogNlzzCh",
	"j3/9aczgJ82qx0pW0QfME27Mq7BoBGV3sANOZDhUQWs0PwbMgbcDxT2+ehe3Lv7+r5FunWerYNvxCDUV",
	"EE0YR5tY3dj8EQF1fEaoVM6is4L2K00wVcxMSl+phRHHfgDT8+7xUcyTMw+dEPk+GCOzVywQ4+pOD4/R",
	"UXcZ7gL4LbFB56wKKaZCXpsGUl6SoXk1EsZTgMBBtwSj/vlwFCsjqpULJVE2IXTCdCASqZtaJ/0TNCRT",
	"SugUxcza/W5mc+bA2tpobbS0Gn2g2CfWgfVa39LuOdOGjUTBgUN0EpiCLEKaAUhO4BaQHoZcNhXoM5Ez",
	"NCGuBO1/mgnH6gUVHtYJSO0CerNeM+TYAwlcWAefvlhEkf0tAB7GefzAcomnh5paYaSY4MCVkcMnHT19",
	"lcDrrTg6KuH1faOcIZtMBFRwzPJr5VulFZVqIbtkLzxlV4jh8jfTPfOHvyoxl8fRUY/k5eW2+cspAnUe",
	"R+9KZShTV7XrbbdapglOJZh6iX3fVamJMLr5qzD7lymThWdCckdUdNTM5aTEe1VQ7KyQfX5nvYR1l95i",
	"lzgo2gpX/HfXy19VI+wildOAI9PPzyZ7HZbZNP/pSllMxBhWRXQm/vW7UfKI9wVLc4daiqD41IsuBdh1",
	"kZCMg4P0m1Wp49Q8fDKfmd/vLFGbFp5NjJwv0GZafqXveAI+EyU2MngLYaSqSoQY1CvaXMJUmYKZ+kzM",
	"2Um79iFzwlWaKMKC93mAozLvfcE3tlbJuM40pxAic/oOHBSB30nguuG3xPJwJ028j8Ln2NuU982nmM27",
	"3da+XhTUO3H/9Gj43ducH2PqoI8bu619lMG/2rsdkNiegWPeeoNs5nlEJmJ8PyUSTf3phqlwf1Ui/FAf",
	"CmoN80ThkF8erTkk5pfG38JijWFhnLcuOL7oFd99eiqqGCH6PBUgnKm+BVc2YxJnPo2XkSXwXa0hUlgY",
	"LzjzDpkFiemOfHvrcPvo9fFOZ/fd3smb92/XDBbLjpZVeHN8HuwF+k9i7Rpv2fT16ZdK8KYwn5wBMsMS",
	"SICR8MFWaVTf0gdnqzGc9iFzzObr9yQfvGamRjR1tyhv2GLjJUdg6jdjQFz9TsHg/VTD3/dP+ig6xPQD",
	"Yrykcn3f73z4wSTVnfU5pQoIyiSasIA6L3UJk7pyNiiy2/vVyxi4BR4iyQMhdYHT7zQQobYbOCoxR51m",
	"jTdMB9pBjEL1GmcY833CdFd2vqFEv4koL3WdE9tFdwFFZjbleFFRYpz8rlLkURcRB6gkMkSS6Tq7gdro",
	"FjiZkJik6eUx6obI5+wWBJIzLJFgHqDPjN9MXPYZMYowRdi2wVeymH1phIXyCpU6WcD1KhqoDQ3tJ3LG",
	"BEQDBcIckJhh5TjjMHI4Dj4TRDIeKvJzTU3tanqYz5macjSmh8fof//5LxJMpWujDeQFQqIxJKqCO2VV",
	"It1woxrU5nx09aA2f9BuzaC24sRYdXjEqvsaEO2OWQ6th388f1WkG6oqxa5NHeTr0xbIx4Q3EHY5YCdE",
	"cEfEy8wmI2ViFcbZTFJWLTa/kHrEbTaiMwE4DhFxfkJqhSmZL9AYVNnAYxfivIOI54FDsAS3Fp3HUbkk",
	"PCf1iGrRVzlXT1+f5jbta1wwqrJrxz9JCMQYCOlupnH3jFAvzd8TLy2roFm/Tw+OVGMk3d3N7n6Jn5AA",
	"m4NEHpbACXYRVQULuYBNEQV0fFiJkEbxJtmT+V/xxEyJmiMxXio2ylukGhSZQogwchmdNl1yq3CIJp7Z",
	"yz3qIhEKCZ7ZBWRBmixNUdhAI7VozB+EQkQgDjLgVAOP9DRUDfTIGH/1wCN7nG/NsKP0aFyV10Xbx386",
	"xGEmr+rXHwBTfCBUKhyQjcNial0eUJiQiuCEqj1m5irIEgBhsBlwD6v51oEJE2cvH0qUnf6r9KznghGR",
	"X/9RQUSJi5tPfitxw9EM7BuNA8xAxCb6KqJUBg3Mx8VPiQrmPiwvg4PRRIlA8TfN2m6vn0eG5GtqbbbE",
	"LoYG0h9qG2uYDljzxnzD+ZC+r1qfYBlwiDojZlJl9km+qlzu6E/ypyDW0uIt7dDW2aH4jWh1B1fN+Vtj",
	"ls95YVnnVf8lm8rt3KFaC0+JjHdk9fGRQKjlss4NZgvrpH9Suo2lEOTQ/KWcp3e/+KDUDLCjT+9FZD82",
	"o49gm3qH5IElsgrwKkS9qbH1A5bYmQ9yl4K6rZUxrQmYk74+wqgzytrR7SF20CCLbF8/BwLArss+g4Mk",
	"Q4EAJGdEmAB57gyys706pD/3GXwJezUC6fOfCO5sAOc5MdDQpLFI2NVW9MU9pqigX1B8i4k5Z1rAYemx",
	"6E9XKvsUDyrPozOdTTOZVLG+/38AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
