// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AdminBearerScopes = "AdminBearer.Scopes"
	OIDCBearerScopes  = "OIDCBearer.Scopes"
)

// Defines values for AuditLogEntryAction.
const (
	AuditLogEntryActionKeyRotate AuditLogEntryAction = "key_rotate"
	AuditLogEntryActionKeyUpload AuditLogEntryAction = "key_upload"
	AuditLogEntryActionSign      AuditLogEntryAction = "sign"
)

// Defines values for ErrorResponseCode.
const (
	AUDITERROR         ErrorResponseCode = "AUDIT_ERROR"
	AUTHINVALID        ErrorResponseCode = "AUTH_INVALID"
	AUTHMISSING        ErrorResponseCode = "AUTH_MISSING"
	INTERNALERROR      ErrorResponseCode = "INTERNAL_ERROR"
	INVALIDREQUEST     ErrorResponseCode = "INVALID_REQUEST"
	KEYDELETEERROR     ErrorResponseCode = "KEY_DELETE_ERROR"
	KEYLISTERROR       ErrorResponseCode = "KEY_LIST_ERROR"
	KEYNOTFOUND        ErrorResponseCode = "KEY_NOT_FOUND"
	KEYPROCESSINGERROR ErrorResponseCode = "KEY_PROCESSING_ERROR"
	KEYUPLOADERROR     ErrorResponseCode = "KEY_UPLOAD_ERROR"
	NOTFOUND           ErrorResponseCode = "NOT_FOUND"
	RATELIMITED        ErrorResponseCode = "RATE_LIMITED"
	RATELIMITERROR     ErrorResponseCode = "RATE_LIMIT_ERROR"
	SIGNERROR          ErrorResponseCode = "SIGN_ERROR"
)

// Defines values for HealthResponseStatus.
const (
	Degraded  HealthResponseStatus = "degraded"
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for KeyUploadResponseSuccess.
const (
	True KeyUploadResponseSuccess = true
)

// Defines values for GetAuditLogsParamsAction.
const (
	GetAuditLogsParamsActionKeyRotate GetAuditLogsParamsAction = "key_rotate"
	GetAuditLogsParamsActionKeyUpload GetAuditLogsParamsAction = "key_upload"
	GetAuditLogsParamsActionSign      GetAuditLogsParamsAction = "sign"
)

// AuditLogEntry defines model for AuditLogEntry.
type AuditLogEntry struct {
	// Action Type of action performed
	Action AuditLogEntryAction `json:"action"`

	// ErrorCode Error code if action failed (omitted on success)
	ErrorCode *string `json:"errorCode,omitempty"`

	// Id Unique audit log entry identifier
	Id string `json:"id"`

	// Issuer OIDC issuer URL or "admin"
	Issuer string `json:"issuer"`

	// KeyId Key identifier involved in the action
	KeyId string `json:"keyId"`

	// Metadata Additional context as JSON string (optional)
	Metadata json.RawMessage `json:"metadata,omitempty"`

	// RequestId Request identifier for correlation
	RequestId openapi_types.UUID `json:"requestId"`

	// Subject OIDC subject claim or "admin"
	Subject string `json:"subject"`

	// Success Whether the action succeeded
	Success bool `json:"success"`

	// Timestamp ISO 8601 timestamp of the action
	Timestamp time.Time `json:"timestamp"`
}

// AuditLogEntryAction Type of action performed
type AuditLogEntryAction string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Machine-readable error code
	Code ErrorResponseCode `json:"code"`

	// Error Human-readable error message
	Error string `json:"error"`

	// RequestId Unique identifier for this request (optional, included for errors from protected endpoints)
	RequestId *openapi_types.UUID `json:"requestId,omitempty"`
}

// ErrorResponseCode Machine-readable error code
type ErrorResponseCode string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Checks struct {
		// Database Status of D1 audit database
		Database bool `json:"database"`

		// KeyStorage Status of Durable Object key storage
		KeyStorage bool `json:"keyStorage"`
	} `json:"checks"`

	// Status Overall health status
	Status HealthResponseStatus `json:"status"`

	// Timestamp ISO 8601 timestamp when health check was performed
	Timestamp time.Time `json:"timestamp"`

	// Version Service version
	Version string `json:"version"`
}

// HealthResponseStatus Overall health status
type HealthResponseStatus string

// KeyMetadata defines model for KeyMetadata.
type KeyMetadata struct {
	// Algorithm Key algorithm
	Algorithm string `json:"algorithm"`

	// CreatedAt ISO 8601 timestamp when key was uploaded
	CreatedAt time.Time `json:"createdAt"`

	// Fingerprint 40-character hex fingerprint
	Fingerprint string `json:"fingerprint"`

	// KeyId Key identifier
	KeyId string `json:"keyId"`
}

// KeyUploadRequest defines model for KeyUploadRequest.
type KeyUploadRequest struct {
	// ArmoredPrivateKey PGP-armored private key in ASCII format
	ArmoredPrivateKey string `json:"armoredPrivateKey"`

	// KeyId Identifier for this key (used in signing requests)
	KeyId string `json:"keyId"`
}

// KeyUploadResponse defines model for KeyUploadResponse.
type KeyUploadResponse struct {
	// Algorithm Key algorithm and bit length
	Algorithm string `json:"algorithm"`

	// Fingerprint 40-character hex fingerprint of the key
	Fingerprint string `json:"fingerprint"`

	// KeyId The uploaded key identifier
	KeyId   string                   `json:"keyId"`
	Success KeyUploadResponseSuccess `json:"success"`

	// UserId User ID associated with the key
	UserId string `json:"userId"`
}

// KeyUploadResponseSuccess defines model for KeyUploadResponse.Success.
type KeyUploadResponseSuccess bool

// GetAuditLogsParams defines parameters for GetAuditLogs.
type GetAuditLogsParams struct {
	// Limit Maximum number of entries to return (1-1000, default 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of entries to skip (for pagination, default 0)
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Action Filter by audit action type
	Action *GetAuditLogsParamsAction `form:"action,omitempty" json:"action,omitempty"`

	// Subject Filter by subject (OIDC subject claim or "admin")
	Subject *string `form:"subject,omitempty" json:"subject,omitempty"`

	// StartDate ISO 8601 timestamp for range start (inclusive)
	StartDate *time.Time `form:"startDate,omitempty" json:"startDate,omitempty"`

	// EndDate ISO 8601 timestamp for range end (inclusive)
	EndDate *time.Time `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// GetAuditLogsParamsAction defines parameters for GetAuditLogs.
type GetAuditLogsParamsAction string

// DeleteKeyParams defines parameters for DeleteKey.
type DeleteKeyParams struct {
	// XRequestID Optional request identifier for correlation
	XRequestID *openapi_types.UUID `json:"X-Request-ID,omitempty"`
}

// GetPublicKeyParams defines parameters for GetPublicKey.
type GetPublicKeyParams struct {
	// KeyId Key identifier. If not specified, uses the default KEY_ID from service configuration.
	// Format: alphanumeric identifier (e.g., "signing-key-v1", "A1B2C3D4")
	KeyId *string `form:"keyId,omitempty" json:"keyId,omitempty"`
}

// SignCommitTextBody defines parameters for SignCommit.
type SignCommitTextBody = string

// SignCommitParams defines parameters for SignCommit.
type SignCommitParams struct {
	// KeyId Key identifier to use for signing. If not specified, uses the default KEY_ID.
	// Must match a key previously uploaded via POST /admin/keys.
	KeyId *string `form:"keyId,omitempty" json:"keyId,omitempty"`

	// XRequestID Optional request identifier. If provided, will be returned in response for correlation.
	// If not provided, a random UUID is generated by the service.
	XRequestID *openapi_types.UUID `json:"X-Request-ID,omitempty"`
}

// UploadKeyJSONRequestBody defines body for UploadKey for application/json ContentType.
type UploadKeyJSONRequestBody = KeyUploadRequest

// SignCommitTextRequestBody defines body for SignCommit for text/plain ContentType.
type SignCommitTextRequestBody = SignCommitTextBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAuditLogs request
	GetAuditLogs(ctx context.Context, params *GetAuditLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListKeys request
	ListKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadKeyWithBody request with any body
	UploadKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UploadKey(ctx context.Context, body UploadKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteKey request
	DeleteKey(ctx context.Context, keyId string, params *DeleteKeyParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminPublicKey request
	GetAdminPublicKey(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPublicKey request
	GetPublicKey(ctx context.Context, params *GetPublicKeyParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SignCommitWithBody request with any body
	SignCommitWithBody(ctx context.Context, params *SignCommitParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SignCommitWithTextBody(ctx context.Context, params *SignCommitParams, body SignCommitTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAuditLogs(ctx context.Context, params *GetAuditLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAuditLogsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListKeysRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadKeyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadKey(ctx context.Context, body UploadKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadKeyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteKey(ctx context.Context, keyId string, params *DeleteKeyParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteKeyRequest(c.Server, keyId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminPublicKey(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminPublicKeyRequest(c.Server, keyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPublicKey(ctx context.Context, params *GetPublicKeyParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPublicKeyRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SignCommitWithBody(ctx context.Context, params *SignCommitParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSignCommitRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SignCommitWithTextBody(ctx context.Context, params *SignCommitParams, body SignCommitTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSignCommitRequestWithTextBody(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAuditLogsRequest generates requests for GetAuditLogs
func NewGetAuditLogsRequest(server string, params *GetAuditLogsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/audit")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Action != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "action", runtime.ParamLocationQuery, *params.Action); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Subject != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "subject", runtime.ParamLocationQuery, *params.Subject); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.StartDate != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "startDate", runtime.ParamLocationQuery, *params.StartDate); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.EndDate != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "endDate", runtime.ParamLocationQuery, *params.EndDate); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListKeysRequest generates requests for ListKeys
func NewListKeysRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUploadKeyRequest calls the generic UploadKey builder with application/json body
func NewUploadKeyRequest(server string, body UploadKeyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUploadKeyRequestWithBody(server, "application/json", bodyReader)
}

// NewUploadKeyRequestWithBody generates requests for UploadKey with any type of body
func NewUploadKeyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteKeyRequest generates requests for DeleteKey
func NewDeleteKeyRequest(server string, keyId string, params *DeleteKeyParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "keyId", runtime.ParamLocationPath, keyId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XRequestID != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Request-ID", runtime.ParamLocationHeader, *params.XRequestID)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Request-ID", headerParam0)
		}

	}

	return req, nil
}

// NewGetAdminPublicKeyRequest generates requests for GetAdminPublicKey
func NewGetAdminPublicKeyRequest(server string, keyId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "keyId", runtime.ParamLocationPath, keyId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/keys/%s/public", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPublicKeyRequest generates requests for GetPublicKey
func NewGetPublicKeyRequest(server string, params *GetPublicKeyParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/public-key")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.KeyId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "keyId", runtime.ParamLocationQuery, *params.KeyId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSignCommitRequestWithTextBody calls the generic SignCommit builder with text/plain body
func NewSignCommitRequestWithTextBody(server string, params *SignCommitParams, body SignCommitTextRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyReader = strings.NewReader(string(body))
	return NewSignCommitRequestWithBody(server, params, "text/plain", bodyReader)
}

// NewSignCommitRequestWithBody generates requests for SignCommit with any type of body
func NewSignCommitRequestWithBody(server string, params *SignCommitParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sign")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.KeyId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "keyId", runtime.ParamLocationQuery, *params.KeyId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XRequestID != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Request-ID", runtime.ParamLocationHeader, *params.XRequestID)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Request-ID", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAuditLogsWithResponse request
	GetAuditLogsWithResponse(ctx context.Context, params *GetAuditLogsParams, reqEditors ...RequestEditorFn) (*GetAuditLogsResponse, error)

	// ListKeysWithResponse request
	ListKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListKeysResponse, error)

	// UploadKeyWithBodyWithResponse request with any body
	UploadKeyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadKeyResponse, error)

	UploadKeyWithResponse(ctx context.Context, body UploadKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*UploadKeyResponse, error)

	// DeleteKeyWithResponse request
	DeleteKeyWithResponse(ctx context.Context, keyId string, params *DeleteKeyParams, reqEditors ...RequestEditorFn) (*DeleteKeyResponse, error)

	// GetAdminPublicKeyWithResponse request
	GetAdminPublicKeyWithResponse(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*GetAdminPublicKeyResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// GetPublicKeyWithResponse request
	GetPublicKeyWithResponse(ctx context.Context, params *GetPublicKeyParams, reqEditors ...RequestEditorFn) (*GetPublicKeyResponse, error)

	// SignCommitWithBodyWithResponse request with any body
	SignCommitWithBodyWithResponse(ctx context.Context, params *SignCommitParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SignCommitResponse, error)

	SignCommitWithTextBodyWithResponse(ctx context.Context, params *SignCommitParams, body SignCommitTextRequestBody, reqEditors ...RequestEditorFn) (*SignCommitResponse, error)
}

type GetAuditLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Count Number of entries in this response
		Count *int             `json:"count,omitempty"`
		Logs  *[]AuditLogEntry `json:"logs,omitempty"`
	}
	JSON400 *ErrorResponse
	JSON401 *ErrorResponse
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAuditLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAuditLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListKeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Keys *[]KeyMetadata `json:"keys,omitempty"`
	}
	JSON401 *ErrorResponse
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListKeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListKeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *KeyUploadResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UploadKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Deleted *bool `json:"deleted,omitempty"`
		Success *bool `json:"success,omitempty"`
	}
	JSON401 *ErrorResponse
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAdminPublicKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAdminPublicKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminPublicKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON503      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPublicKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetPublicKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPublicKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SignCommitResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON429      *struct {
		Code  *SignCommit429Code `json:"code,omitempty"`
		Error *string            `json:"error,omitempty"`

		// RetryAfter Seconds until rate limit resets
		RetryAfter *int `json:"retryAfter,omitempty"`
	}
	JSON500 *ErrorResponse
	JSON503 *ErrorResponse
}
type SignCommit429Code string

// Status returns HTTPResponse.Status
func (r SignCommitResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SignCommitResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAuditLogsWithResponse request returning *GetAuditLogsResponse
func (c *ClientWithResponses) GetAuditLogsWithResponse(ctx context.Context, params *GetAuditLogsParams, reqEditors ...RequestEditorFn) (*GetAuditLogsResponse, error) {
	rsp, err := c.GetAuditLogs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAuditLogsResponse(rsp)
}

// ListKeysWithResponse request returning *ListKeysResponse
func (c *ClientWithResponses) ListKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListKeysResponse, error) {
	rsp, err := c.ListKeys(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListKeysResponse(rsp)
}

// UploadKeyWithBodyWithResponse request with arbitrary body returning *UploadKeyResponse
func (c *ClientWithResponses) UploadKeyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadKeyResponse, error) {
	rsp, err := c.UploadKeyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadKeyResponse(rsp)
}

func (c *ClientWithResponses) UploadKeyWithResponse(ctx context.Context, body UploadKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*UploadKeyResponse, error) {
	rsp, err := c.UploadKey(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadKeyResponse(rsp)
}

// DeleteKeyWithResponse request returning *DeleteKeyResponse
func (c *ClientWithResponses) DeleteKeyWithResponse(ctx context.Context, keyId string, params *DeleteKeyParams, reqEditors ...RequestEditorFn) (*DeleteKeyResponse, error) {
	rsp, err := c.DeleteKey(ctx, keyId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteKeyResponse(rsp)
}

// GetAdminPublicKeyWithResponse request returning *GetAdminPublicKeyResponse
func (c *ClientWithResponses) GetAdminPublicKeyWithResponse(ctx context.Context, keyId string, reqEditors ...RequestEditorFn) (*GetAdminPublicKeyResponse, error) {
	rsp, err := c.GetAdminPublicKey(ctx, keyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminPublicKeyResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// GetPublicKeyWithResponse request returning *GetPublicKeyResponse
func (c *ClientWithResponses) GetPublicKeyWithResponse(ctx context.Context, params *GetPublicKeyParams, reqEditors ...RequestEditorFn) (*GetPublicKeyResponse, error) {
	rsp, err := c.GetPublicKey(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPublicKeyResponse(rsp)
}

// SignCommitWithBodyWithResponse request with arbitrary body returning *SignCommitResponse
func (c *ClientWithResponses) SignCommitWithBodyWithResponse(ctx context.Context, params *SignCommitParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SignCommitResponse, error) {
	rsp, err := c.SignCommitWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSignCommitResponse(rsp)
}

func (c *ClientWithResponses) SignCommitWithTextBodyWithResponse(ctx context.Context, params *SignCommitParams, body SignCommitTextRequestBody, reqEditors ...RequestEditorFn) (*SignCommitResponse, error) {
	rsp, err := c.SignCommitWithTextBody(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSignCommitResponse(rsp)
}

// ParseGetAuditLogsResponse parses an HTTP response from a GetAuditLogsWithResponse call
func ParseGetAuditLogsResponse(rsp *http.Response) (*GetAuditLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAuditLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Count Number of entries in this response
			Count *int             `json:"count,omitempty"`
			Logs  *[]AuditLogEntry `json:"logs,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListKeysResponse parses an HTTP response from a ListKeysWithResponse call
func ParseListKeysResponse(rsp *http.Response) (*ListKeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListKeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Keys *[]KeyMetadata `json:"keys,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUploadKeyResponse parses an HTTP response from a UploadKeyWithResponse call
func ParseUploadKeyResponse(rsp *http.Response) (*UploadKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest KeyUploadResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteKeyResponse parses an HTTP response from a DeleteKeyWithResponse call
func ParseDeleteKeyResponse(rsp *http.Response) (*DeleteKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Deleted *bool `json:"deleted,omitempty"`
			Success *bool `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAdminPublicKeyResponse parses an HTTP response from a GetAdminPublicKeyWithResponse call
func ParseGetAdminPublicKeyResponse(rsp *http.Response) (*GetAdminPublicKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminPublicKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetPublicKeyResponse parses an HTTP response from a GetPublicKeyWithResponse call
func ParseGetPublicKeyResponse(rsp *http.Response) (*GetPublicKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPublicKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseSignCommitResponse parses an HTTP response from a SignCommitWithResponse call
func ParseSignCommitResponse(rsp *http.Response) (*SignCommitResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SignCommitResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest struct {
			Code  *SignCommit429Code `json:"code,omitempty"`
			Error *string            `json:"error,omitempty"`

			// RetryAfter Seconds until rate limit resets
			RetryAfter *int `json:"retryAfter,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9x8a3MaubP3V1HNbtVj5wEMDvZueHWwTRziG2vwZi/k2GKmAcUzmllJY5uT8nc/1ZLm",
	"xgwYO85J/TeVF2bQSK1W96+v4qvjhkEUcuBKOp2vjnTnEFD9Zzf2mDoNZz2uxAIfRCKMQCgG+mvqKhZy",
	"/MsD6QoWmY/OaBEBCafEfE8iENNQBOA5NQd4HDidvx3JZtypObewuI4jP6Se/SBCRRU4n2uOWkTgdByp",
	"BOMz57HmgBChOAw9KC/Yw6+IG3pAWLrslDIfPLIVBkwp8EjIiYxdF6TcdiqmZ1553ivO/omBUGQD8cMZ",
	"AWQEYR5wxaYMROVEUsYgypNd9I8OifmSXF2eklCQsUO9gPGxUzXPLSz6FTSdQJ4Awvhd6N+BRxgnag52",
	"81XzBaCoRxUtT9n1PIZ/Up+4IVfwoAiV5OPw4pyY18lWGJkByDo8TKqcjvNFVq8k4J8YpKqi/tJ8ld/B",
	"VB+dEOBTS3q6QBwzr2oBGU++gKtW8Nh+S1yfsuBJNluZKM/1aQ5qDiLHVSM/4EGOqEkY+kA5zqRYAFLR",
	"ICrP1R9ekF/3my2SjkH9KJxXummPKqjjuDK1lrdMgIdKZJiTrppnfM1JJ7bymHEtEa1s75m6hWbIY83o",
	"1CXIKORSqxw80CDy9Z+u1kLnpPfn9fnF6Pr9xdX5kWM11IooDxWZhjH3cK4ibLiVOnxG3TnjUBdAPTrx",
	"gUCq1Dnc6F6NPlyf9YfD/vmxUzMf++e/d0/7SMAyQfh5cHlx2NPjr3uXlxeX9vFpfzgqPLganF50jwqP",
	"jnqnvVEvfTTsH5+nHy67o971af+sP6p41MPFLVnXl73frnrDkab2KDc8T2j/fNS7PO+e2i9Xwl+ZbR/i",
	"gPJlpgUgJZ3BM3XTot2Saqo5k8S+leFAjTDu+rEHnh6kl5VkKsKARCJU4CLiAveikHElt59W6iXRNrut",
	"GVmpEs8PQH01z8vnkpDNwb2V5eeIgBMqKwRwqKiKJerlUctCfjq4St1vYTFUoUA+r5srFvpgLgwm3cKC",
	"SPtWedIlJuRWqGWEV3FD6vUq8PAOBPV9MtfcInZYpk7m+QKnh5mgBtlinjyuksPnodz9HHiyuj4Sck9l",
	"wSPYBPdqzh0IWelrDEHcMRdIMuApwUpZkMfN7GUrNlU8PoHFWc6ELrlC/iwUTM2DaoOdfV3LcNQRkrab",
	"7/ar9usKoAq8rtqcyyhayFzjTz2Dt1PGZyAiwXjFau1m3Z1TQV0FgszhgeRH15yIKgUCB/733936+2b9",
	"3eev7ebjzy92aJ48wMR2FenIMzjj3YpjvNIcsq5IxVmKIBTgDQS7owpOYFGmeXA8qNthJDLjNP8ZJ93h",
	"Yb9PLOc350K/AnVxxq1YGucOPWZ0xSwUVzmxKzhV3s8TfFmFqZsKOaHcIxN0mYHP1HxTmX+xHCa+1C0s",
	"XkckR3NI1cic61qPP+dCWmBVIobPVUYjliAqba8EQfpHhEoZugzFl9wzNc9tK2Ph0EpCAn3juNl866J8",
	"gPgvO6zhhoF+/rQXmVBf20C1LPll+UEugBsLphZDjB+NwHTR7T4AKkw8NNF/vU9ASYW3wLXpWTadzCVm",
	"LNFjtEZoF55JJahid0BQLnW8IBtjPgRF7hglN/eC8pkPgkhwBSgSxYp0j87659eji5Pe+U1jzMe8bzwX",
	"rayxmoeC/Y+eCe2UB6JDbgqPO8TswPJZU2RYezNG8nW8rI/ZbDTlzVypCM8cg5KVTPj4aVRigY5i7M7R",
	"ozpm6kM8IV3t0UuMaI6ZOqUTctjXGyp+3yEj/Sq9o8zXvgeV5Obnr18tU2TjuD/6cHVgWEIeH2/IlpUH",
	"SW6YV9crd8i9YApu0FYHTKJ53LZrmZVXLHPYv/54cXD98dPoBgnNP7j+ffcGp0DtMrtjktxRn3la3icL",
	"4yEwPuuMeatBUM6pigUQOqOMS0U+fjoZZl4l2XKpOzfoePL79pjvNkjfxNdM4kPq++E9eMRn6Lp2T08v",
	"PvWOrvvD4VXvcrg95m8bdg9M6ngFHiJUCrIFD5GJHrfHvN0g3dhjwF0gAVXuHCQONB7uHfVjIFu9Pwa9",
	"w1Hv6Bo9/N75YW97E8lApWF8GpqYiCtqIlpO9TvdQZ8M4ygKBSphLHz7nuzs7MyYmscT1PGd2y+UU7Uz",
	"i2Z1ayHq0uACit5SmsSbQd2DyA8X4KEMETcMAqZS24JrxhL/uoiAD44H+ht9BrJhjo5JYudHR/+OeSAJ",
	"ymsdfVMvncmlEZ0wn6Hp0Op72N85PCIRi8BnHCTZKgptLRPp7TFH+7Gk74jCAeV0BgFwZcDRDYNIwBy4",
	"xBFplmbG+ExT+9NPWsERul2tyubhT2QQT3zmkl4iSWNeJ+choYXBJAFJ/PYSLbzPAqZQPMkARD2RQ+LB",
	"lMY+zmJnTwOgXiaqO8iZbZzqzRut3xZUtAC+eUO2ntJ0/e6lJWkzqAqZ59aLeFXaSavZTF0K1HUSMB4r",
	"0H+ajJU2fWqR7E5jemFn+qR23tjNLe8rB78v2IKe+6k97FduwUqAyQ1+oNzzGZ/hw67v2zhZWFdHJtFs",
	"B2e/0V/edMi62FoPxOj0pkPWpC7IloT8Z0km4If3mhM3aSx+0yE2+BbV+TEPJrGW61wmDrfSy03MuIeS",
	"C0RG4LIpc02yUXbMueQzJ2/edCpNH9FIj1xK37BZDHyjzzVYo1QmSGkORo8u5F5wuPWvrQflhZCALJMq",
	"e2U5PYNvml1FIkS/BDetJ6CKZq/lszXZK8Znwzc43ONb2Qv5XE72ggc+KLuCGZsleXBU4mql3obNKpux",
	"+YSP3nEqlgQeTKKQbFnJkkSAEovuVIGwmrKUIMIZzqhvAuNEEJKTSBNH5uiSfDTOyeCO+gW6itkkfOOK",
	"pyYL0RtsxsaqiKb71KoTPivoF4lRQYzBnsTuLajM02/k92xCa6QpFtyY5UTBrHwZWbz5o45v6QXrlxBQ",
	"hjy+SSUGp7APcQ43FsJAPvfC+4oJJCijQA/LIbGhS+AIjc6f8KFIKQavRj6MRgPS3n1H0nO6yQ7qBtXX",
	"DbknScwV880ZkiiUkk182G5oM+8zF2y8ZG33WX/0Mpu9M/HDyU5ApQKxc9o/7J0PeybporTrfzw4Jsvu",
	"f3fQz6UwOk6r0Ww08aUwAk4j5nSct41Wo2lCo7l2zC1ma5OJn2egqnL1WrhALhVA0KRr+5tAEZkyX4Eu",
	"FEwWNqNdS9LwNR0NootH0DmHxpgP6Ixxo042t2jcLnNcERU0AFSTxphfJo5pzh3AYKBgqc0xpDqK8ZVz",
	"DCqpXkm9czupdDp/l1PPDyyIA8LjYAICo8lkmyq04ky2WvVWs9msJdYeDed2Pizba6I353Scf2IQGLBZ",
	"WdCbSpxBW3zRMzidVrNZcwKzuP6EHxm3H1NvkXEFMxAYZC1Tfl5FsbxlEdlCsxGljM7oLlK9guhwOpWw",
	"guo8kc1NiHyvpUOLhpYjW0zRL+bjWlsTrKInLWZk9Ly4kriOwKR0tPVEIanAQydYCIjCFaRnVZeM9icp",
	"qsjx4XlqBUKcFcoaFvR8i8TsNnfb9War3myNms2O/v/XKtJwoiPkUp64zQpRz6IYuPckvW9bo923nb13",
	"nb13q+gF7r2M2s81J3X18KXdZjMJusAkm2gU+RZNdnRZc7ngFeO4Vs3xEU8QQpLidyq2iDpawOvNZiur",
	"u2UWQJvQhnlPNow9iCUISwaahjQJY6ZFy3ALi/odzpfVb52vYwclTjIVisXY6Yyd8J6D2MGHY6c21sWC",
	"U518GzudvfbuY6E42HH29prwa7vZrMPuu0m93fLadfpLa7/ebu/v7+21281ms5mrGHZy8+fKhh0lYihU",
	"BNLTbO2NWs3O22anvddo7b79y3n8/Jg/tuWKYFyV8yujmy5ya5thc5Rl/EmO6KvDFAT6j58FTJ2O89NO",
	"1uiwY7scdootDo/pfFQIutB5reVMVymsTt0xmfhj6GYZHk1j39fTtp8vcrrGWq4iJlXWxB3PQJ7krFyB",
	"2+sYUKzzVmzvyXXazdYGW3slas5MhIJozCxhRWcAKdrbiNmvRNF702diXAV9+pm/JAuZUY0bhZzo358R",
	"m2QcBFQsnI7zGwJe/vWao6gGHPOe8xnns97bLSzkOuctFlySBDVMDtX30wwNvp341r4pSmZdJNYdRV8t",
	"V90IKHp51Nf5MtBRxEMUSvAapJ94z7r4os17ggpSO4DFLLr8FtfulEl1gnv/VlQ3DPy7UNjIFShyNbjV",
	"uLZUtnBau2/be/u//Pqu2T04POq9X/V5NdKjbc0TBN7u3l7r3SqCmqNWu7OLNDXae/tlgtaTkX1eRdDu",
	"euhOhHAjsM2XUF8EtXjsa0H2PxOJqltrCi0qCepXoI0+gtfD+5UrPAvJUElLeFMBZzUnCmUFfplaJGIH",
	"qSq0qjCPUxrcYgn5OmmhQGSKDhqD8iUHBCYLfHpn4OsSbrFnA98/QfRLkHQrp2C1LBeybYJZm/zAqf1w",
	"NjOYahBdCcp8Tc2Lsc+w5URXBK1DdxB6i+fJWEWB26njv4Pecf+cDI4HZHDZ/7076pGT3p/k4PTi8ER/",
	"P+aNRmPM9d+986M1I9fB24aCWirUPxYrl+h8PpZMQOuZrKhE/teG9JLLnJSBn1vLfQnzVms6SnVa5v7+",
	"DmsCmCXxQwg1nHt9rzXtXLOpbTJl4Htye3NzUd7iUtdhsr8rTm1OHV5zJ9/dzix1Pi7HF4iaaTvLs4PI",
	"1+NDJq022f1Mi2T0gVBdG8hZpSd97J2vWjgfjZHyQVU0/A1ABJQbV9qMkYTmVzGV/KJvraupWWnBpZyH",
	"ikyAxNwLOTQIbtmUKEyqNDMounW4YFRebFKONLkntndmTZo0NaFZbUqFdrelRF4B/XQyJ6K6FcjmcpJe",
	"kyKePytJdpGkn8UmTeWaBlOGyKj4o26NS11rckVaaUW36jdnlAzbsm3n7cMadzt97WtFc1GuD6mis3QT",
	"59qe5r/Hs351n9gwSOPG8+DHqFkRFDaGnp1IdyxsUKpBYDCDta6mm9X3cRJnN+dJN8b8SsI09rXK3IFg",
	"06T/IQnbPQQTNolN6icWGPLLb63N4CumDeNFyPN/gDfPU/FoFtWTWLgCRuzXFUhSkrVBdnr/SZFuu9l+",
	"sQey0SWSV3QjCvP+ICCx7Q0vQJJj3diYColO7GVNH/hIG7MqZDGd+CthZGD68mWhY1+S0DSXJ8G2BxFw",
	"D7jLQJKt3I2GpNKr7ymY6q1JQnqgzL5lei9CpwbiiVxIBYFcgRLmksc35/myuyDZ7Q+j/fk7HInltVcp",
	"cncjNipwVJbgN5OapbssVSUG5JZhFUno0qL79ntwYkp9WWBF7nLIj+fFBQdEIowhU56kBGpNSjXlQ/7i",
	"SdKvl1MN+z0G17v7tivQaopRMI3ZmxndNEu1rJkzdmdvZ/SPjLXVva7H6LuHxuIucn2WxGZ5cYwOF6y7",
	"kIUNiVYNjgd1Y2BUcV0ZM6UTWEgAC6JQKNNLo0Lb9cmnbBaLdQZ6Y9tcvL7RIP2phleLR+DVbP/QHNIW",
	"BIT8/pGJiBJQWabJNEh3CPWjOeVxAIK5eQd/CxqzRo2Ml4z/2MFn3dbB7uHbo/bYMY24T7kKS3Xm9Hrk",
	"d/ANMlKWM25XB6f9w1LC7XejSJ2kI7fxRZK7fdSpMT8MgwC46pCkwhxGwKNZ9EU2QqEbuR6+nPX+mvTb",
	"8vLPjyf3fx4cdD/Qs4ocXvXa1RHR67sy/2rHoZrwilup5Qx/3kX4oamXPlcgMNLONw8uYW2ChgkQVYc5",
	"axBX91FgwFtZDxiyGZdJy7mXNK7rfLzpWNeBT65CgL6IsEhJebmhvZiHN17t8y5eZPcTmNSBFlUMUVf3",
	"xh0z9f8kOR4cZysWoqu0KJEkLyahtyByHsa+p2/hU5vlgQfqqsJ+VajnJFtqETGX+v4itRl66ZsZU2RO",
	"5bxuYv2bbbvXYi9m0vGYa4gkjBs1T8I/SuJiXzLCto7xPN0bWmU8kC2HmtznmQ7cVyyN0bLC8wxr0hjz",
	"s1gqc0WDUC0CkYA7FsbSz6W57xglg4vhiOSi7Mb3MRLPSVjpnSbSXSP3zPfJBKp7aZdyW40xt1zK3qdE",
	"UO6FAbm66h+heM6A4xnl3IrUnShsfcPGoO+QTFtVy1LwoHYin7IimjpKABA6cVu7b8c8orpF2INpe29/",
	"bPPw5JwGSUUFAsr8ckGFZLUc8v9xb2NuNE3BC18fW9nP3cFfLSEloL2k91Wq3iCjVNXx8MJYRbFO6ZR0",
	"veE8XSNrbsjiJQ9l2D8+746uLnuv4prcR3/2upe9g+6se3zw20dffmGtbjf82BuU/ZPllVc7JinYbuKe",
	"ZACe4GfBN6lZCddcq+xZX9eyJiqb2XNYa/rZC1tZ31frlNreK3/DodQFX1rTdsRXiebScpk+v+jXIvKm",
	"YvtZkPD4XSqQ52FBuxK8/NHO1YpKJdL4b6tTtnffvWgrS7+tkmyl4saNPszkAofTae+t7Ts1v0ST9JIX",
	"Vln7IywZSFaTUPG7KxlN5d+wKNwxySZM9TRdrr1XiQxP1naqqczhG7rvi/oTBKqQ3FOmyASmoQBzGwb3",
	"txZIHr8hVCr85E45QDKwTfKg/wMVedVlsZdl6pblvsSGpGVEQRCFggqGbi5Pr2P/YF6sJ45s5W5hobmc",
	"+ozDdjkRnr87v5wHR37n8TwXZtqjwMhyaUY9hY5iqyKSgQi92FxPAX7HRMjRiynf5YpmjVv65Ta8p768",
	"ZQ3uO2Vv/zR0qU88uAM/jPSl5VVTdnZ2fBw8D6Xq/PrLr784SKXdy9fqnErhN3WSSl12HTB3SZ4vX2ze",
	"zlz2ynC8InDpHx3Ws991Wro1nnXaZRMnB1Ceq7v2XrcOOtPbZlR7Y2Sr8GMQiXeb24YpcTx+fvzfAAAA",
	"//+uvKS0zFAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
