name: CI
on: { push: { branches: [master] }, pull_request: { branches: [master] } }

jobs:
  verify-api:
    name: Verify API Generation
    runs-on: ubuntu-latest
    steps: [uses: actions/checkout@v7, uses: ./.github/actions/check-api-changes]

  format:
    name: Format check
    runs-on: ubuntu-latest
    steps: [uses: actions/checkout@v7, uses: ./.github/actions/check-formatting]

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps: [
      uses: actions/checkout@v7,
      uses: ./.github/actions/setup-task,
      uses: ./.github/actions/setup-bun,
      { run: task typecheck },
    ]

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps: [
      uses: actions/checkout@v7,
      uses: ./.github/actions/setup-task,
      uses: ./.github/actions/setup-bun,
      uses: ./.github/actions/setup-go,
      uses: ./.github/actions/setup-golangci-lint,
      { run: task lint },
    ]

  test:
    name: Test
    runs-on: ubuntu-latest
    steps: [
      uses: actions/checkout@v7,
      uses: ./.github/actions/setup-task,
      uses: ./.github/actions/setup-bun,
      { run: task test },
    ]
